### ISSUE TITLE
Add a topic in docs showing extension methods for AppSettings dependencies

### ISSUE THREAD

**Issue by jeremydmiller** [structuremap/structuremap#150]
/// <summary>
        /// Sets the value of the constructor argument to the key/value in the 
        /// AppSettings when it exists. Otherwise uses the provided default value.
        /// </summary>
        /// <param name="appSettingKey">The key in appSettings for the value to use.</param>
        /// <param name="defaultValue">The value to use if an entry for <paramref name="appSettingKey"/> does not exist in the appSettings section.</param>
        /// <returns></returns>
        public TInstance EqualToAppSetting(string appSettingKey, string defaultValue)
        {
            var propertyValue = ConfigurationManager.AppSettings[appSettingKey];
            if (propertyValue == null) propertyValue = defaultValue;
            _instance.Dependencies.Add(_propertyName, typeof (TChild), propertyValue);
            return _instance;
        }

**Comment by jeremydmiller** [comment]
Meh, sorry. I'm going to kill this permanently. It's just too easy to do this yourself and who knows what's happening now with configuration in the DNX new world order.

**Comment by jeffdoolittle** [comment]
Fair enough, thanks!
