### ISSUE TITLE
"Interception and Decorators" Topic

### ISSUE THREAD

**Issue by jeremydmiller** [structuremap/structuremap#203]

**Comment by eddiegroves** [comment]
I've enjoyed the doco so far and I'm really looking forward to this one :+1:

**Comment by NightOwl888** [comment]
I know that documentation is time consuming to do, but having something is better than having nothing. Couldn't you at least link each topic to the applicable unit test page on GitHub?

I had to search quite a bit to work out how to use the decorator pattern, and ended up stumbling across the link to the unit tests in issue #302. But my search would have been much shorter if the link to the unit tests were [here](http://structuremap.github.io/interception-and-decorators/) instead.

In fact, it might be helpful to keep the unit test link there even after the documentation is completed.

**Comment by jeremydmiller** [comment]
@NightOwl888 Sigh, sadly enough the docs really aren't going to be much more than the tests with a little bit of verbiage. I'm on vacation starting in a day or two, but I'll try to get back to doing docs again the week after.

**Comment by NightOwl888** [comment]
All I am saying is, the verbiage would be ideal. A link to the unit tests would be acceptable. Nothing at all is unacceptable.

It seems that adding a hyperlink would be something quick and easy to accomplish, even if it isn't ideal.

**Comment by NightOwl888** [comment]
And not just for this topic, but each topic that directly corresponds to unit tests.

**Comment by jeremydmiller** [comment]
@NightOwl888  "Nothing at all is unacceptable." -- it's a **free as in beer** OSS project that takes community pull requests on the documentation.
