### ISSUE TITLE
Operation could destabilize the runtime? Fails on some machines

### ISSUE THREAD

**Issue by mschreibernaoual** [structuremap/structuremap#254]
I am getting this issue on my machine, but other dev machines are working ok. Same source, setup, etc..  Has anyone seen this before?

Operation could destabilize the runtime.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Security.VerificationException: Operation could destabilize the runtime.

Source Error: 

Line 25:         public static IContainer Initialize()
Line 26:         {
Line 27:             ObjectFactory.Initialize(x => x.Scan(scan =>
Line 28:             {
Line 29:                 scan.TheCallingAssembly();

**Comment by satish860** [comment]
Can you please let me know HotFix URL to fix the same .

**Comment by jdiapps** [comment]
We updated the windows machine to the latest hotfixes
