### ISSUE TITLE
How can I get IContext.BuildStack.Current.RequestedType after StructureMap update?

### ISSUE THREAD

**Issue by vorou** [structuremap/structuremap#288]
I updated the SM from 2.6.4.1 to 3.1.0.133 and this code became broken:

```
For(typeof(MongoCollection<>)).Singleton().Use(c => GetMongoCollection(c));
...
private static object GetMongoCollection(IContext containerContext)
{
    var collectionFactory = containerContext.GetInstance<MongoCollectionFactory>();
    var collectionType = containerContext.BuildStack.Current.RequestedType;
    var documentType = collectionType.GetGenericArguments()[0];
    var createMethod =
        typeof(MongoCollectionFactory).GetMethod(CreateMethodName, new Type[0])
                                        .MakeGenericMethod(documentType);
    return createMethod.Invoke(collectionFactory, null);
}
```

the reason is there is no longer `BuildStack` property in `IContext`. I looked around and didn't find a way to get requested type in new version of SM, is there any?

**Comment by vorou** [comment]
Finally made it.

I basically copy-paste the part from the [test](https://github.com/structuremap/structuremap/blob/977b1784632484473d09d3724f2435a73437e49b/src/StructureMap.Testing/Acceptance/builder_for_open_generic_type.cs). Here's what's my code looks like:

```
public MongoRegistry()
{
    For(typeof (MongoCollection<>)).Use(new MongoCollectionInstanceFactory());
}

public class MongoCollectionInstanceFactory : Instance
{
    public override Instance CloseType(Type[] types)
    {
        var instanceType = typeof (MongoCollectionInstance<>).MakeGenericType(types);
        return Activator.CreateInstance(instanceType) as Instance;
    }
...
}

public class MongoCollectionInstance<T> : LambdaInstance<MongoCollection<T>>
{
    public MongoCollectionInstance()
        : base(c => c.GetInstance<MongoCollectionFactory>().Create<T>())
    {
    }
}
```

I only kind of understand what's happening here, but still it looks cleaner than our previous 73 level reflection master implementation. Thanks for the help!

**Comment by jeremydmiller** [comment]
Gonna close that then if that is okay.

**Comment by tkirill** [comment]
Found great description of the solution for this issue in the official docs: http://structuremap.github.io/generics/ (Example #2: Generic Instance Builder)
