### ISSUE TITLE
The docs site points to old documentation.

### ISSUE THREAD

**Issue by wallymathieu** [structuremap/structuremap#292]
The pages found on [docs.structuremap.net](http://docs.structuremap.net/QuickStart.htm) are out of date.

It should maybe point to the github.io pages?

**Comment by docrinehart** [comment]
+1 bump! I'm pretty new to structuremap and having a hard time finding good resources on using it effectively.

**Comment by wallymathieu** [comment]
Perhaps a way is to point to the new documentation in the readme and in the wiki?

**Comment by jeremydmiller** [comment]
The readme and the nuget both point to the new documentation site. @docrinehart, if you didn't find it, the new docs are at http://structuremap.github.io. They're still not complete, but I'm restarting work on them (coincidentally) either today or early next week.

**Comment by docrinehart** [comment]
Ah... I had thought those were new docs, but it is still labeled v1.0.0, so I assumed that it was still old documentation. I'll bookmark it and keep my eye open though. Thanks.

**Comment by jeremydmiller** [comment]
@docrinehart I might have the version number fixed in the next couple days. I'm converting the docs to a different set of tooling before I get started on authoring again.

**Comment by jeremydmiller** [comment]
@docrinehart Actually, could you go look at it now? I put the new website up just now.

**Comment by docrinehart** [comment]
Ooh, bootstrap! =D

**Comment by jeremydmiller** [comment]
I give up. Shutting this off. You'd think that at some point the freaking DNS name on structure map.net would expire and go away. We literally do not remember where in the hell the docs are published anymore.
