### ISSUE TITLE
Adding a bunch of types to the Scanning and Convention Pipeline to enable internal classes.

### ISSUE THREAD

**Issue by DerAlbertCom** [structuremap/structuremap#315]
Sometimes i would like to add internal types to StructureMap. Which works with if i add them one by one in a Registry.

It would be nice if i can add an IEnumerable<Type> of types (which i gather with reflection inside the assembly) to the Assembly Scanner so that i can also add internal types and use all defined conventions, filters and so on.

```
Scan(s=>{
   s.AddTypes(()=> SomeMagicWithReturnSomeTypes();
   sWithDefaultConvention();
});
```

Any Interest?

**Comment by jeremydmiller** [comment]
Nothing has happened on this one for awhile, so I'm closing it in the interest of bookkeeping

**Comment by DerAlbertCom** [comment]
Ups, lost Focus ;) Maybe i give them a shot.
