### ISSUE TITLE
Ability to modify instance after instance is requested from container

### ISSUE THREAD

**Issue by bryancrosby** [structuremap/structuremap#319]
I have seen this scattered somewhat across a few posts since SM3 was released.  I think we are all saying the same thing.

I know there is some general abuse of AOP, but proxy interception is one of the few simplistic and nice things that Castle.Core adds for cross-cutting concerns in applications.

Consider a simple convention that registers IExecutor

    public interface IExecutor()
    {
        void Execute();
    } 

    public class Executor : IExecutor
    {
        private readonly IDependency aDependency;
        private readonly IOtherDependency bDependency;

        public Executor(IDependency aDependency, IOtherDependency bDependency)
        {
            this.aDependency = aDependency; //auto-wired from DefaultConventionScanner()
            this.bDepdenency = bDependency; //auto-wired from DefaultConventionScanner()
        }

        public void Execute()
        {
            aDependency.DoSomethingInteresting(); //intercepted with proxy
            bDependency.DoSomethingInterestingAgain(); //intercepted with proxy
        }
    }

    public class ExecutorConventionScanner : ConfigurableRegistrationConvention
    {
        public override void Process(Type type, Registry registry)
        {
            if (type.IsConcrete() && type.CanBeCastTo<IExecutor>())
            {
                registry.For(typeof(IExecutor)).Add(type);
            }
        }
    }
Now if we have a convention scanner that is looking for things at run-time, we don't necessarily know the dependencies of `Executor` are.  We are making an assumption that in this code base the following is known.
 1. Executor is requested from the container
 2. All dependencies in the constructor can be accessed from the container

Given that, it would be nice to do the following (or if there is a way to do it already, I must be missing it)
 * Have a complete default, regular, instance of IExecutor, where all of the dependencies are of the default type.
* * e.g., Executor([default of runtime discovered dependency], [another default of runtime discovered dependency])
 * Have a proxied IExecutor, which itself is a proxy, and all of it's dependencies are proxies.
* * ProxiedExecutor([proxy of runtime discovered dependency], [proxy of another runtime discovered dependency])

I have not had much success using `DecorateWith` or an interceptor here because I cannot access the created instance in order to create the proxy.  I have the *types*, but I don't have the built instances.  Using `Castle.Core`, `CreateInterfaceProxyWithTargetInterface` requires the `object` target and the interface type.

Using `IInterceptorPolicy`, we have access to the types, but not the instances.

**Comment by jeremydmiller** [comment]
@bryancrosby Sorry I dropped this. Did anything become of this? I'm not sure what you mean about not having access to the actual instances in the interception, because as far as I can tell, you do.

**Comment by bryancrosby** [comment]
@jeremydmiller Oh wow, I need to jog my memory :) I will post in gitter so we don't clog up this channel

**Comment by DixonD-git** [comment]
@bryancrosby I know this is an old issue and you may not remember details, but have you tried to use `FuncInterceptor` in combination with `Castle.Core` for creating proxies? That's what I do in similar scenarios (although I don't use `Castle.Core` at the moment). Also, from what I understand, this issue is relevant to #364 raised by me.

**Comment by jeremydmiller** [comment]
@bryancrosby Actually, I'm going to call this one closed with the new construction policy feature in 4.0 that was meant to deal with basically this type of scenario: http://structuremap.github.io/registration/policies/
