### ISSUE TITLE
Generic Inheritance Parent -> Child Issue

### ISSUE THREAD

**Issue by ak99372** [structuremap/structuremap#320]
Structuremap won't resolve instance of class implementing IGeneric{IChild} when another class implements IGeneric{IParent}  (IChild inherits from IParent). Somehow the parent implementation blocks off the child implementation (even though WhatDoIHave shows correct scan). Test case to demonstrate this:

        interface IParent { }; 
        interface IChild : IParent { }
        public class ConcreteChild : IChild { }

        public interface IGeneric<in T> where T : class { }
        public class GenericClass1 : IGeneric<IParent> { }
        public class GenericClass2 : IGeneric<IChild> { }

        [Test]
        public void StructureMap_Resolves_Child_Interface()
        {
            //Verify Default Inheritance
            Assert.IsTrue(typeof(IGeneric<ConcreteChild>).IsAssignableFrom(typeof(GenericClass1)));
            Assert.IsTrue(typeof(IGeneric<ConcreteChild>).IsAssignableFrom(typeof(GenericClass2)));

            var container = new Container(cfg =>
            {
                cfg.Scan(scan =>
                {
                    scan.TheCallingAssembly();
                    scan.ConnectImplementationsToTypesClosing(typeof(IGeneric<>));
                });
            });

            var instances = container.GetAllInstances<IGeneric<ConcreteChild>>();
            Assert.IsTrue(instances.Any(t => t.GetType() == typeof(GenericClass1)));
            Assert.IsTrue(instances.Any(t => t.GetType() == typeof(GenericClass2)));
        }

<b>The last assert will Fail unless GenericClass1 is commented out then it will Pass. </b>

UPDATED:
I created another unit test but with classes. The same issue occurs

        public class Parent { };
        public class Child : Parent { }
        public class ConcreteChild : Child { }

        public interface IGeneric<in T> where T : class { }
        public class GenericClass1 : IGeneric<Parent> { }
        public class GenericClass2 : IGeneric<Child> { }
        //public class GenericClass3 : IGeneric<ConcreteChild> { }

        [Test]
        public void StructureMap_Resolves_Generic_Child_Classes()
        {
            Assert.IsTrue(typeof(IGeneric<ConcreteChild>).IsAssignableFrom(typeof(GenericClass1)));
            Assert.IsTrue(typeof(IGeneric<ConcreteChild>).IsAssignableFrom(typeof(GenericClass2)));
            //Assert.IsTrue(typeof(IGeneric<ConcreteChild>).IsAssignableFrom(typeof(GenericClass3)));

            var container = new Container(cfg =>
            {
                cfg.Scan(scan =>
                {
                    scan.TheCallingAssembly();
                    scan.ConnectImplementationsToTypesClosing(typeof(IGeneric<>));
                });
            });

            var what = container.WhatDoIHave();

            var instances = container.GetAllInstances<IGeneric<ConcreteChild>>();
            Assert.IsTrue(instances.Any(t => t.GetType() == typeof(GenericClass1)));
            Assert.IsTrue(instances.Any(t => t.GetType() == typeof(GenericClass2)));
            //Assert.IsTrue(instances.Any(t => t.GetType() == typeof(GenericClass3)));
        }

<b>If you uncomment GenericClass3 this will PASS.</b>

**Comment by ak99372** [comment]
I created another unit test with classes. The issue persists

**Comment by jeremydmiller** [comment]
@ak99372 I'm finally on this this morning. Thank you for the test.

**Comment by jeremydmiller** [comment]
@ak99372 I can reproduce the problem. It's gonna take some all new code to make this work.

I think this is probably the same root cause as @jbogard 's GH-323 bug.
