### ISSUE TITLE
If an exception is thrown when a singleton is created the stack is hidden

### ISSUE THREAD

**Issue by pablocastilla** [structuremap/structuremap#321]
When something fails in the constructor of a singleton the only error I get is "Bi-directional dependency relationship detected!" and the stack is not shown.

The stack and the exception message should be shown to help tracing errors.

**Comment by jeremydmiller** [comment]
@pablocastilla I need a lot more context than that to help you out here. Can you put some reproduction steps or a failing UT in here?

**Comment by jeremydmiller** [comment]
@pablocastilla See the commit tagged to this issue. Feel free to reopen this issue if you're still having trouble.

**Comment by morstaine** [comment]
I see this behavior often. I will try to put together a failing UT and add it here.

**Comment by morstaine** [comment]
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using StructureMap;

namespace ReproduceStructureMapBiDiProblem
{
    [TestClass]
    public class ReproduceBiDiProblem
    {
        [TestMethod]
        public void Singleton_WhenFailsToConstruct_ShouldNotThrowBiDiErrorsOnFurtherAttemptsToConstruct()
        {
            var container = new Container(_ => 
                _.ForSingletonOf<SomeSingletonThatConnectsToDatabaseOnConstruction>()
                    .Use<SomeSingletonThatConnectsToDatabaseOnConstruction>());

            // 1st attempt : database is down, expect "Database is down" exception
            DatabaseStatus.DatabaseIsDown = true;

            try
            {
                // If the database is down, the construction of the instance will fail.
                var attempt1 = container.GetInstance<SomeSingletonThatConnectsToDatabaseOnConstruction>();

                Assert.Fail("Expected container.GetInstance to throw Exception");
            }
            catch (Exception ex)
            {
                // The first time we attempt, we get a valuable error
                Assert.IsTrue(ex.ToString().Contains("Database is down"));
            }

            // 2nd attempt : database is still down, still expect "Database is down" exception
            try
            {
                // If the database is down, the construction of the instance will fail.
                var attempt2 = container.GetInstance<SomeSingletonThatConnectsToDatabaseOnConstruction>();

                Assert.Fail("Expected container.GetInstance to throw Exception");
            }
            catch (Exception ex)
            {
                // The second time we attempt, we _should_ get a valuable error, but get a bi-di error

                // This assert currently fails in SM 3.x
                Assert.IsTrue(ex.ToString().Contains("Database is down"));
            }

            // The database has now come online.
            DatabaseStatus.DatabaseIsDown = false;
            
            // If the database is up, the construction of the instance should now succeed, but
            // instead still throws a bi-di error
            var attempt3 = container.GetInstance<SomeSingletonThatConnectsToDatabaseOnConstruction>();

            // This assert also fails in SM 3.x
            Assert.IsNotNull(attempt3);
        }
    }

    public static class DatabaseStatus
    {
        public static bool DatabaseIsDown { get; set; }
    }

    public class SomeSingletonThatConnectsToDatabaseOnConstruction
    {
        public SomeSingletonThatConnectsToDatabaseOnConstruction()
        {
            if (DatabaseStatus.DatabaseIsDown)
                throw new Exception("Database is down");
        }
    }
}

**Comment by morstaine** [comment]
Opened new issue https://github.com/structuremap/structuremap/issues/329 for this.
