### ISSUE TITLE
Class with multiple constructors cannot be selected if parameter is not a primitive type

### ISSUE THREAD

**Issue by jonswaino** [structuremap/structuremap#322]
public class IoC
			{
				public static IContainer Init()
				{
					var container = new Container(x =>
					{
						x.Scan(s => {
							s.TheCallingAssembly();
							s.AssembliesFromApplicationBaseDirectory();
							s.WithDefaultConventions();                   
						});
						x.For<IActivityService>().Singleton();

						x.ForConcreteType<ClassWithTwoConstructors>()
							.Configure.SelectConstructor(() => new ClassWithTwoConstructors(new AnotherDependency()))
							.Ctor<AnotherDependency>("anotherDependency").Is(new AnotherDependency());
												
					});

					container.WhatDoIHave();
					return container;
				}
			}

	 public class AnotherDependency
		{
			public AnotherDependency()
			{
			}
		}

		public class ClassWithTwoConstructors
		{
			

			public ClassWithTwoConstructors(int age, string name)
			{
			  
			}

			public ClassWithTwoConstructors(AnotherDependency anotherDependency)        
			{
				
			}
		}

		public class MainService
		{
			public MainService(IStoryService storyService,
							   ClassWithTwoConstructors anotherDependency)
			{
				
			}
		}

The MainService constructor cannot be instantiated with the AnotherDependency parameter.

**Comment by jeremydmiller** [comment]
@jonswaino I'm looking at this now.

**Comment by jeremydmiller** [comment]
@jonswaino,

It was a bit of an edge case with the constructor selection. My expression visitor was finding the inner constructor in this case. Without waiting for 3.1.5, you can work around it by:

``` C#
            var container = new Container(x =>
            {
                x.Scan(s =>
                {
                    s.TheCallingAssembly();
                    s.AssembliesFromApplicationBaseDirectory();
                    s.WithDefaultConventions();
                });
                x.For<IActivityService>().Singleton();

                
                x.ForConcreteType<ClassWithTwoConstructors>()
                    .Configure.SelectConstructor(() => new ClassWithTwoConstructors(new AnotherDependency()))
                    .Ctor<AnotherDependency>().Is(anotherDependency);

                    // You don't need to specify the argument name if there is only 1 for that type
                    //.Ctor<AnotherDependency>("anotherDependency").Is(anotherDependency);

            });
```

**Comment by jonswaino** [comment]
Ok great thanks for this.
