### ISSUE TITLE
CreateChildContainer and policies

### ISSUE THREAD

**Issue by qjuanp** [structuremap/structuremap#324]
Hello,

Any recommendation to replicate all policies registered in main container to new child container through CreateChildContainer call? 

Currently, my custom IIntercptorPolicy registered in container is called only when I resolve an object with main container, the child container created on base of main container hasn't any interceptor policy

**Comment by jeremydmiller** [comment]
@qjuanp I'm looking into this right now.

**Comment by jeremydmiller** [comment]
I can reproduce the bug. Fix coming now.

**Comment by qjuanp** [comment]
Great! Thanks a lot @jeremydmiller
