### ISSUE TITLE
FillAllPropertiesOfType bug in SM 3 or am I missing something?

### ISSUE THREAD

**Issue by mdmoura** [structuremap/structuremap#327]
Hello,

With SM 3 I tried to inject an object into a class property. For that I created the following example:

    public partial class HomeController : Controller {
      public ISettings Settings { get; set; }
      public HomeController(ISettings settings) {
        var fromProperty = Settings;
        var fromContructor = settings;
      }
    }

Settings is injected in constructor but not in property. My Structure Map 3 configuration is:

    For<ISettings>().Singleton().Use<Settings>();

    Policies.FillAllPropertiesOfType<ISettings>().Singleton().Use<Settings>();

Might this a bug or am I missing something here?

Thank You,
Miguel

**Comment by jeremydmiller** [comment]
@mdmoura,

Can you put a failing unit test to reproduce the problem in the issue?

Thanks,

Jeremy

**Comment by jeremydmiller** [comment]
@mdmoura See https://github.com/structuremap/structuremap/blob/e61c431a83cce0a0fef89f776c24215b73506fab/src/StructureMap.Testing/Bugs/FillAllProperties_Bug_327.cs.

As far as I can tell, everything is working as it's supposed to. You aren't trying to get at the value of the setter property in your constructor function are you? That will never work because the ctor has to be called first to create the object before any of the setter resolution would work.

**Comment by mdmoura** [comment]
@jeremydmiller Yesterday, I did a similar test and wasn't able to reproduce either.

I just created a sample MVC application 10 minutes ago, where I use http://www.nuget.org/packages/StructureMap.MVC5 and I checked on HomeController Settings from constructor and property. The constructor is not null the property one is null:

    https://github.com/mdmoura/StructureMap3WebTest/blob/master/StructureMap3WebTest/StructureMap3WebTest/Controllers/HomeController.cs

Here is the registry:

    https://github.com/mdmoura/StructureMap3WebTest/blob/master/StructureMap3WebTest/StructureMap3WebTest/DependencyResolution/DefaultRegistry.cs

And on container setup when I check WhatDoIHave I get the two Singletons:
    https://github.com/mdmoura/StructureMap3WebTest/blob/master/StructureMap3WebTest/StructureMap3WebTest/App_Start/StructuremapMvc.cs

And the configuration does not throw any exception.

Does any of this help?

**Comment by mdmoura** [comment]
>> You aren't trying to get at the value of the setter property in your constructor function are you?

Yes, that was the problem ... Didn't realize that.
