### ISSUE TITLE
Can SM auto-register generics?

### ISSUE THREAD

**Issue by vorou** [structuremap/structuremap#328]
Auto-registration works as expected for non-generic types:

```
public interface IHypeProvider
{
    string GetHype();
}

public class HypeProvider : IHypeProvider
{
    public string GetHype()
    {
        return "hype";
    }
}
...
var container = new Container(_ =>
                                {
                                    _.Scan(s =>
                                            {
                                                s.TheCallingAssembly();
                                                s.RegisterConcreteTypesAgainstTheFirstInterface();
                                            });
                                });
Console.Out.WriteLine(container.GetInstance<IHypeProvider>().GetHype());
```

However, if the type is generic, it blows up with `No default instance is registered`:
```
public interface IProfitGenerator<T>
{
    string GetProfit<T>();
}

public class ProfitGenerator<T> : IProfitGenerator<T>
{
    public string GetProfit<T>()
    {
        return "profit";
    }
}
...
var container = new Container(_ =>
                                {
                                    _.Scan(s =>
                                            {
                                                s.TheCallingAssembly();
                                                s.RegisterConcreteTypesAgainstTheFirstInterface();
                                            });
                                });
Console.Out.WriteLine(container.GetInstance<IProfitGenerator<int>>().GetProfit<int>());
```

Unless I explicitly register it with:
```
_.For(typeof (IProfitGenerator<>)).Use(typeof (ProfitGenerator<>));
```

1. Is there a way to auto-register (e.g., `RegisterConcreteTypesAgainstTheFirstInterface`) all the generics w/o specifying them explicitly?
2. If there isn't, then why? Is it not implemented because it's hard/impossible, or just because nobody else feel bad about naming all the generic types in container configuration?

I asked a similar question [on SO](http://stackoverflow.com/questions/17289396/can-structuremap-auto-register-handlert-for-ihandlert).

**Comment by LetMeCodeThis** [comment]
[My answer on SO](http://stackoverflow.com/a/28668981/4336786)

**Comment by vorou** [comment]
@LetMeCodeThis check the comment on SO.

In short, what I'm looking for is the way to auto-register generic types as the interface they implement w/o registering them explicitly, just like it is for non-generic types.

**Comment by jeremydmiller** [comment]
@LetMeCodeThis Did you try this:  https://github.com/structuremap/structuremap/blob/master/src/StructureMap.Testing/Graph/GenericConnectionScannerTester.cs?

And yes, you can do conventional scanning against Open Generic types.

**Comment by jeremydmiller** [comment]
@vorou,

The logic in the `RegisterConcreteTypesAgainstTheFirstInterface` is just too naive for what you're wanting to do. The check is for interfaces implemented directly by the concrete type. In the case of an open generic, you need to dig into the generic template type to find the interface. As stated before, you can write your own registration scanner. I'd also accept a pull request to enhance the built in convention for open generic types if you'd like to do that.

Otherwise, I'm closing this issue for now.
