### ISSUE TITLE
Question, not issue

### ISSUE THREAD

**Issue by RolandPheasant** [structuremap/structuremap#331]
Sorry as this is not an issue, just a question

I have a generic object which implements 2 interfaces. The following object must be a singleton e.g.

Object ```MessageBroker<T>``` implements ```IMessagePublisher<T>``` and ```IMessageListener<T>```

Can I do this generically at registration time?

```csharp
For<MessageBroker<T>>().Singleton();
Forward<MessageBroker<T>, IMessagePublisher<T>>();
Forward<MessageBroker<T>, IMessageListener<T>>();
```
If this is already do-able then I apologise up front for wasting you time

**Comment by jeremydmiller** [comment]
@RolandPheasant Can you put this on the user list instead? https://groups.google.com/forum/#!forum/structuremap-users

**Comment by RolandPheasant** [comment]
Of course. Thanks for a quick response.

**Comment by jeremydmiller** [comment]
Closing, but I'll go answer the question.
