### ISSUE TITLE
A bug in the IModel.GetAllPossible implementation in StructureMap 3.1.4.143

### ISSUE THREAD

**Issue by belgaard** [structuremap/structuremap#337]
My scenario is that I want to identify all caches in my code (under test),
IEnumerable<ICachedData> allPossible = _container.Model.GetAllPossible<ICachedData>().ToList();

This will fail with an error,
Collection was modified; enumeration operation may not execute

It looks like a ToList() on AllInstances will fix this issue.

My work around for now is to use the following explicit implementation (I cannot pull/push GitHub form where I am now),

	    private IEnumerable<ICachedData> AllPossibleCacheInstances
	    {
		    get
		    {
			    IEnumerable<InstanceRef> allInstances = _container.Model.AllInstances.ToList();
			    return
				    allInstances.Where(x => TypeExtensions.CanBeCastTo(x.ReturnedType, typeof(ICachedData)))
					    .Select(x => x.Get<ICachedData>())
					    .Where(x => (object)x != null);
		    }
	    }

**Comment by jeremydmiller** [comment]
@belgaard The *permanent* fix will be in a later version when I try to use immutable structures to prevent this kind of problem. For now, I *think* that https://github.com/structuremap/structuremap/commit/46fd794d7c1899203dd59a6aeec63dec29d7f4ef will alleviate this. The fix will be in 3.1.6 a couple days after the July 4th holiday.
