### ISSUE TITLE
Adding Structuremap.automocking via NuGet adds Wrong structuremap refrence in packages.config

### ISSUE THREAD

**Issue by jakejgordon** [structuremap/structuremap#340]
I've noticed on several projects now that when I add a reference to structuremap.automocking to a project that doesn't already have structuremap then it adds the following to the packages.config:

```
      <package id="structuremap" version="3.0.0.108" targetFramework="net451" />
      <package id="structuremap.automocking" version="3.1.5.154" targetFramework="net451" />
```

Everything then compiles, but it starts giving weird runtime errors saying methods are missing and such. However, if I install structuremap first, and then install structuremap.automocking separately then everything is OK. I think there is something fishy with the NuGet configuration.

**Comment by jeremydmiller** [comment]
I just switched to Paket for constructing nugets, and it takes care of the versioning of dependencies for you.
