### ISSUE TITLE
Default Instance not found

### ISSUE THREAD

**Issue by schotime** [structuremap/structuremap#341]
Here is an example of a program that is failing when trying to resolve open generic types. Maybe I'm doing something wrong. Cheers.

**Exception:**
Unhandled Exception: StructureMap.StructureMapBuildPlanException: Unable to crea
te a build plan for concrete type MyGenericOperation<Data>

new MyGenericOperation<Data>(Func<Data, Boolean>, Int32 something)
  ? Func<Data, Boolean> = \*\*Default**
                      Int32 something = Required primitive dependency is not exp
licitly defined

1.) Attempting to create a BuildPlan for Instance of IOperation<Data> -- MyGenericOperation<Data>
2.) new OpProcesor`1(Enumerable of IOperation<Data> with all registered instances)
3.) OpProcesor<Data>
4.) Instance of OpProcesor<Data>
5.) Container.GetInstance(OpProcesor<Data>)

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using StructureMap;

namespace ConsoleApplication7
{
    public class Program
    {
        public static IContainer Container;

        static void Main(string[] args)
        {
            var container = new Container();
            container.Configure(conf =>
            {
                conf.Scan(x =>
                {
                    x.AssemblyContainingType<Data>();
                    x.WithDefaultConventions();
                    //x.AddAllTypesOf(typeof (IOperation<>)).NameBy(z=>z.Name);
                    x.ConnectImplementationsToTypesClosing(typeof (IOperation<>));
                });
            });

            Container = container;

            Program.Container.GetInstance<OpProcesor<Data>>().Process();
        }
    }

    public class Data
    {
        public string Name { get; set; }
    }

    public class OpProcesor<T>
    {
        private readonly IOperation<T>[] _operations;

        public OpProcesor(params IOperation<T>[] operations)
        {
            _operations = operations;
        }

        public void Process()
        {
            
        }
    }

    public class MyOp2 : IOperation<Data>
    {
        public IEnumerable<Data> Execute(IProcessContext context, IEnumerable<Data> data)
        {
            return data;
        }
    }
    
    public class MyOp : MyGenericOperation<Data>
    {
        public MyOp() : base(x=>x.Name == "test", 1)
        {
        }
    }

    public class MyGenericOperation<T> : IOperation<T>
    {
        private readonly Func<T, bool> _someParam;

        public MyGenericOperation(Func<T, bool> someParam, int something)
        {
            _someParam = someParam;
        }

        public IEnumerable<T> Execute(IProcessContext context, IEnumerable<T> data)
        {
            //Generic
            return data.Where(_someParam).Select(x => x);
        }
    }

    public interface IOperation<T>
    {
        IEnumerable<T> Execute(IProcessContext context, IEnumerable<T> data);
    }

    public interface IProcessContext
    {
    }
}
```

**Comment by jeremydmiller** [comment]
@schotime This code is your culprit: `public MyGenericOperation(Func<T, bool> someParam, int something)`. StructureMap can't automatically infer usage for "primitive" constructor or setter arguments. You need to explicitly register this type w/ arguments for `something`.

**Comment by jeremydmiller** [comment]
Hey, and could you paste in WhatDoIHave() results here too?

**Comment by schotime** [comment]
==========================================================================================================
PluginType           Namespace               Lifecycle     Description                           Name     
----------------------------------------------------------------------------------------------------------
Func<TResult>        System                  Transient     Open Generic Template for Func<>      (Default)
----------------------------------------------------------------------------------------------------------
Func<T, TResult>     System                  Transient     Open Generic Template for Func<,>     (Default)
----------------------------------------------------------------------------------------------------------
IContainer           StructureMap            Transient     Object:  StructureMap.Container       (Default)
----------------------------------------------------------------------------------------------------------
IOperation<Data>     ConsoleApplication7                                                                  
                                             Transient     ConsoleApplication7.MyOp2                      
                                             Transient     ConsoleApplication7.MyOp                       
                                             Transient     MyGenericOperation<Data>                       
----------------------------------------------------------------------------------------------------------
IOperation<T>        ConsoleApplication7                                                                  
                                             Transient     MyGenericOperation<T>                          
                                             Transient     ConsoleApplication7.MyOp                       
----------------------------------------------------------------------------------------------------------
Lazy<T>              System                  Transient     Open Generic Template for Func<>      (Default)
==========================================================================================================

**Comment by schotime** [comment]
Here is what 2.6.4.1 does:

```


================================================================================================================================================================================================================================
PluginType                                  Name                                     Description                                                                                                                                
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Func`1<TResult> (Func`1<TResult>)                                                                                                                                                                                               
Scoped as:  Transient

                                            bf84bb76-4e63-417c-9c8d-034e196d6f5b                                                                                                                                                
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IOperation`1<T> (IOperation`1<T>)                                                                                                                                                                                               
Scoped as:  Transient

                                            0d9c8010-c379-4d12-9b0d-b2459809f7e0     Configured Instance of ConsoleApplication7.MyGenericOperation`1, ConsoleApplication7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IContainer (StructureMap.IContainer)        66ef72ce-7ded-42d5-8788-ed41dcccfaa7     Object:  StructureMap.Container                                                                                                            
Scoped as:  Transient

                                            66ef72ce-7ded-42d5-8788-ed41dcccfaa7     Object:  StructureMap.Container                                                                                                            
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IOperation`1<Data> (IOperation`1<Data>)                                                                                                                                                                                         
Scoped as:  Transient

                                            324073e0-fce2-4e09-bb59-d101d445d727     Configured Instance of ConsoleApplication7.MyOp2, ConsoleApplication7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null               
                                            1fcc391a-28ea-4f3d-b779-bffa99e23643     Configured Instance of ConsoleApplication7.MyOp, ConsoleApplication7, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null                
================================================================================================================================================================================================================================
```

**Comment by jeremydmiller** [comment]
What's the WhatDoIHave() output for 3?

**Comment by schotime** [comment]
Its the first one. Already posted.

**Comment by schotime** [comment]
Looks like this line is the culprit.

```
Operation<Data>     ConsoleApplication7                                                                  
                                             Transient     ConsoleApplication7.MyOp2                      
                                             Transient     ConsoleApplication7.MyOp                       
                                             Transient     MyGenericOperation<Data>                       
```

Doesn't return the generic one in 2.6.4.1.

**Comment by jeremydmiller** [comment]
Yeah, but `MyGenericOperation<Data>` *can* be cast to `Operation<Data>`, right? So according to all the goofy co/contravariance rules, that's correct behavior.

**Comment by jeremydmiller** [comment]
You might just need to force the defaults here.

**Comment by jeremydmiller** [comment]
Hey @schotime, since this isn't really a bug, can you close this when you're satisfied? I don't feel like there's any change to be made to SM3 on this one.
