### ISSUE TITLE
Intermittent problems loading MVC5 application

### ISSUE THREAD

**Issue by tenfortyeight** [structuremap/structuremap#353]
We have intermittent problems loading up an Asp.net MVC5 application. The problem occurs when running container.BuildUp() for filters.

The class that crashes looks like this:
`
	public class StructureMapFilterProvider : FilterAttributeFilterProvider
	{
		private readonly IContainer _container;
		public StructureMapFilterProvider(Func<IContainer> container) : base(false)
		{
			_container = container();
		}
		
		public override IEnumerable<Filter> GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor)
		{
			var filters = base.GetFilters(controllerContext, actionDescriptor);

			foreach (var filter in filters)
			{
				_container.BuildUp(filter.Instance);
				yield return filter;
			}
		}
	}`

The stacktrace looks like the following:
`
[NullReferenceException: Object reference not set to an instance of an object.]
   StructureMap.BuildSession.BuildUp(Object target) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\BuildSession.cs:45
   StructureMap.Container.BuildUp(Object target) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Container.cs:304
   DagensIndustri.Weekend.Web.DependencyResolution.<GetFilters>d__2.MoveNext() in C:\code\DagensIndustri.Weekend.Web\DagensIndustri.Weekend.Web\DependencyResolution\StructureMapFilterProvider.cs:23
   System.Web.Mvc.FilterProviderCollection.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +210
   System.Web.Mvc.ControllerActionInvoker.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +51
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +237
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState) +41
   System.Web.Mvc.Async.WrappedAsyncVoid'1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +66
   System.Web.Mvc.Async.WrappedAsyncResultBase'1.Begin(AsyncCallback callback, Object state, Int32 timeout) +169
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +885
   System.Web.Mvc.Async.WrappedAsyncResultBase'1.Begin(AsyncCallback callback, Object state, Int32 timeout) +170
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +699
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState) +94
   System.Web.Mvc.Async.WrappedAsyncVoid'1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +67
   System.Web.Mvc.Async.WrappedAsyncResultBase'1.Begin(AsyncCallback callback, Object state, Int32 timeout) +170
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +563
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +921
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157`

**Comment by jeremydmiller** [comment]
Okay, timeout a second. What exactly are you passing into BuildUp()? The IEnumerable itself, or are you looping through each filter object and calling BuildUp() on each one?

**Comment by tenfortyeight** [comment]
The second one, looping over the filters and then calling BuildUp on each of the filters.

**Comment by jeremydmiller** [comment]
What's the type it blows up on?

**Comment by tenfortyeight** [comment]
DagensIndustri.Core.Web.Utils.Attributes.RequestEventFilter : ActionFilterAttribute

**Comment by tenfortyeight** [comment]
After some more investigation I can conclude that the behavior is consistent. The first request after a compile is always successful, all subsequent requests will fail with the above error. If I recompile or do an iisreset the first request then succeeds again, but the following fails.

It's like the container is disposed and then never recreated. Using the Structuremap.MVC5 package for the base wiring of the application.

**Comment by tenfortyeight** [comment]
Hmm... removal of the DisposalOfNestedContainer on EndRequest solves the problem. However, I'm unsure what kind of effects that will have?

			context.EndRequest += (sender, e) =>
			{
				HttpContextLifecycle.DisposeAndClearAll();
				//StructuremapMvc.StructureMapDependencyScope.DisposeNestedContainer();
			};

**Comment by jeremydmiller** [comment]
I think one of two things is happening to you, you're either accidentally disposing the main container, or you're trying to reuse the same nested container on all requests and it's getting disposed after the first request.

**Comment by tenfortyeight** [comment]
Solved by not injecting the IContainer to the ctor of StructureMapFilterProvider and rather getting the root-container as a variable in the scope. Otherwise the application container which lives between requests could be used for this case since the FilterProvider is long lived but the filters are instantiated on each request.
