### ISSUE TITLE
Are 3.1.4.X versions backwards compatible ( assembly redirect is not working)?

### ISSUE THREAD

**Issue by YogirajA** [structuremap/structuremap#362]
In my project, I am using Structuremap with Assembly Version=3.1.4.0.  One of the assemblies my project is dependent on is using assembly version 2.6.4.0. I get the error below when I try to instantiate anything in that assembly

*Could not load file or assembly 'StructureMap, Version=2.6.4.0, Culture=neutral, PublicKeyToken=e60ad81abae3c223' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference*
 
It looks like a classic assembly redirect problem. I added it in config file like below:

    <dependentAssembly>
        <assemblyIdentity name="StructureMap" publicKeyToken="e60ad81abae3c223" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.4.0" newVersion="3.1.4.0" />
    </dependentAssembly>

It didn't make any difference. Are 3.1.4.X versions backwards compatible? I don't have any control over the assembly I am dependent upon but I need to use it.

**Comment by jeremydmiller** [comment]
@YogirajA And that's a big no. Per semver rules, 3.0 introduced breaking API changes.

**Comment by YogirajA** [comment]
@jeremydmiller I thought so. I may have to go back to 2.X versions to resolve this. Do you have any other ideas? Thanks for the quick reply!

**Comment by jeremydmiller** [comment]
@YogirajA I think you're going to have to go back to 2.6.4 in your own usage. It's worse in a way because I removed strong naming for 3.0.

**Comment by YogirajA** [comment]
@jeremydmiller Ok Thanks!
