### ISSUE TITLE
Interception with dynamic proxy

### ISSUE THREAD

**Issue by DixonDs** [structuremap/structuremap#364]
From what I understand, it is not possible to make interception with using dynamic proxies. The closest thing is `DecoratorInterceptor` but you have to provide a concrete decorator implementation each time for each type you decorate. What I like to have is a dynamic proxy interceptor where I could define some common logic which doesn't depend on the specific class. 

Currently, I achieve this by using the combination  of `FuncInterceptor` from `StructureMap` and `Intercept.ThroughProxy` from `Unity.Interception`. Ideally, I would like to use `StructureMap` only.

I could start working on adding this feature to `StructureMap` but I would like to gather some input first whether this feature is desirable at all and if yes, in what direction I should go - implement dynamic proxy generation from scratch or use something like `Castle.Core`

**Comment by jeremydmiller** [comment]
@DixonD-git Have you looked at using a combination of `IInterceptorPolicy` and probably a subclass of FuncInterceptor to get this done? I'm really thinking that the existing plugin points should cover you here.

**Comment by DixonD-git** [comment]
@jeremydmiller Could you provide an example? I don't really understand what `IInterceptorPolicy ` is for, I should investigate the code more. Although I want to stress once more on the key point of the feature I need - dynamic proxies. In some cases like logging, caching etc you don't want to implement decorators for all classes you have, but rather have the code the intercepts every method call. Like here in `Unity` documention (look for `LoggingInterceptionBehavior`, for instance): https://msdn.microsoft.com/en-us/library/dn178466%28v=pandp.30%29.aspx .

**Comment by jeremydmiller** [comment]
@DixonD-git Haven't forgotten you on this one, just got busy and forgot about it:(. I'll try to get this on the docs tomorrow maybe. Worse case scenario, I'll write the sample code for the docs and link that to you.

**Comment by jeremydmiller** [comment]
I moved out the dynamic interception to https://github.com/structuremap/StructureMap.DynamicInterception

**Comment by NTTAKR** [comment]
Hi Jeremy, 

I quite don't understand. You said you would move it out to StructureMap.DynamicInterception and when I look there, it says "Obsolete, look at main repository". 

The place in the documentation about dynamic interception is blank. Not very helpful :-(

Thanks for your input.

**Comment by DixonDs** [comment]
@NTTAKR It was moved out to a separate repo, but after some time a decision was made to move it back to this repo.

As for documentation, it is in my to-do list, sorry, that it takes too long for me to do it. In the meantime please check https://github.com/structuremap/structuremap/blob/master/src/StructureMap.DynamicInterception.Testing/DynamicProxyInterceptorAcceptanceTests.cs, the usage is quite simple.

**Comment by NTTAKR** [comment]
Hi Dmytro,

thanks for your quick reply.
I think I might have an out of date version, because the ISyncInterceptorBehavior does not exist in StructureMap.
I installed from NuGet using the latest version.

I’ll try again by using the current GitHub code.

Best regards,
  Andreas Kroll

NTT-SolutionWare GmbH
Andreas Kroll
Am Hang 1G
40822 Mettmann
Germany

Tel:      +49 (2104) 175 7590
Fax:      +49 (2104) 175 7591
Mobil:   +49 (151) 5288 2476

Sitz der Gesellschaft:          Mettmann                            Bank:                      VR-Bank Mainz
Handelsregisternummer:  HRB 21698                           IBAN:                     DE05 5509 1200 0080 9125 01
Amtsgericht:                        Wuppertal                            BIC:                        GENODE61AZY
Geschäftsführer:                 Andreas Kroll                       Kontoinhaber:     NTT-SolutionWare GmbH

**Comment by DixonDs** [comment]
@NTTAKR it is in a separate package: https://www.nuget.org/packages/structuremap.dynamicinterception

**Comment by NTTAKR** [comment]
That is very strange. 
I searched for something like that, and I tried it again a few minutes ago: 
Nuget does not show any packages for structuremap.dyn*

**Comment by NTTAKR** [comment]
OMG.... I just verified: 

If you write structuremap.dyn or Structuremap.dyn NUGET does NOT find any package at all. 

If you capitalize the M => structureMap.dyn it works

OMG what a big failure....

**Comment by NTTAKR** [comment]
Hi again,

I managed to install the necessary Nuget package and tried to implement a Method interception like in the test files, but was unable to do that.
I always get an exception stating:

StructureMap.Building.StructureMapInterceptorException

"Decorator Interceptor failed during object construction.  See the inner exception
1.) DynamicProxyInterceptor of test1.ILog with interception behaviors: test1.NegatingInterceptor
2.) test1.ConsoleLogger
3.) Instance of test1.ILog (test1.ConsoleLogger)
4.) new Application(*Default of ILog*, *Default of Mediator*)
5.) test1.Application
6.) Instance of test1.Application
7.) Container.GetInstance<test1.Application>()
"

{"Der Typeninitialisierer für \"StructureMap.DynamicInterception.DynamicProxyInterceptor`1\" hat eine Ausnahme verursacht."}
"Fehler beim Versuch der SecurityTransparent-Methode \"StructureMap.DynamicInterception.DynamicProxyInterceptor`1<TPluginType>..cctor()\", auf die sicherheitskritische Methode \"Castle.DynamicProxy.ProxyGenerator..ctor()\" zuzugreifen.\n\nDie Assembly \"StructureMap.DynamicInterception, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\" ist mit \"AllowPartiallyTrustedCallersAttribute\" markiert und verwendet das Sicherheitstransparenzmodell der Stufe 2. Bei Festlegung der Transparenz auf Stufe 2 werden alle Methoden in AllowPartiallyTrustedCallers-Assemblys standardmäßig sicherheitstransparent, was die Ursache der Ausnahme sein kann."

What can I do to be able to use interception?

The code:

public class NegatingInterceptor : ISyncInterceptionBehavior
    {
        public IMethodInvocationResult Intercept(ISyncMethodInvocation methodInvocation)
        {
            var argument = methodInvocation.GetArgument("value");
            var argumentValue = (int)argument.Value;
            if (argumentValue < 0)
            {
                argument.Value = -argumentValue;
            }
            return methodInvocation.InvokeNext();
        }
    }


    class Program
    {
        static void Main(string[] args)
        {
            InitIoc();
        }

        private static void InitIoc()
        {
            var container = new Container(cfg =>
            {
                cfg.Policies.Interceptors(new DynamicProxyInterceptorPolicy(new NegatingInterceptor()));

                cfg.Scan(scanner =>
                {
                    scanner.TheCallingAssembly();

                    scanner.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>));
                    scanner.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<,>));
                    scanner.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<>));
                    scanner.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<>));
                    scanner.ConnectImplementationsToTypesClosing(typeof(INotificationHandler<>));
                    scanner.ConnectImplementationsToTypesClosing(typeof(IAsyncNotificationHandler<>));
                });
                cfg.For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
                cfg.For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));
                cfg.For<IMediator>().Use<Mediator>();

                cfg.For<ILog>().Use<ConsoleLogger>();

            });

            //Console.WriteLine(container.WhatDoIHave());

            var app = container.GetInstance<Application>();
            app.Run().Wait();
            Console.WriteLine("Waiting on Return");
            Console.ReadLine();
        }
   }



Best regards,
  Andreas Kroll

**Comment by DixonDs** [comment]
@NTTAKR Could you report your issue separately? This thread is closed and cannot be really used for tracking all issues related to dynamic interception
