### ISSUE TITLE
MoqAutoMocker.UseConcreteClassFor<>() doesn't seem to do anything

### ISSUE THREAD

**Issue by jdehlin** [structuremap/structuremap#409]
I have an ICacher interface with a Cacher implementation. This get's injected in some places that I want to unit test. I'm using MoqAutoMocker to wire things up, but in the tests I would like to use the concrete Cacher rather than a mock. I've tried quite a few different things but using UseConcreteClassFor<>() doesn't seem to have any effect.

**Comment by jeremydmiller** [comment]
@jdehlin That's not exactly what that method is for, that would only apply if you were taking in a dependency on that exact concrete type instead of any kind of interface or abstract base class.

How about Inject<ICacher>(your cacher)?

**Comment by jdehlin** [comment]
That got it. Thanks for your help!
