### ISSUE TITLE
Structuremap container configuration errors after upgrade

### ISSUE THREAD

**Issue by Azazel666** [structuremap/structuremap#411]
We have in a project upgraded from version 2.6.4.1 of structuremap to 3.1.6.186.
Now some of our container configurations here is two type examples of configurations that no longer work.

Example 1:
```
c.For<Func<string, CartHelper>>()
                .HybridHttpOrThreadLocalScoped()
                .Use(cartName => new CartHelper(cartName, PrincipalInfo.CurrentPrincipal.GetContactId()));
```
In version 2.x cartName was resolved as string from Func<string, CartHelper> but now we get Structuremap.IContext interface.

Example 2:
```
c.For<Func<CultureInfo>>().Use(() => ContentLanguage.PreferredCulture);
```
Here we get "There is no implicit reference conversion between CultureInfo and Func<CultureInfo>. If the Func<> is removed it works but im not sure it will be the same as it was intended as.

**Comment by Azazel666** [comment]
we have found a solution, this code is bootstrap code for another product that we use for a base when creating new commerce sites. They already had a fix for this issue.

Example 1 is fixed like this:
```
c.For<Func<string, CartHelper>>()
                .HybridHttpOrThreadLocalScoped()
                .Use(cartName => new Func<string, CartHelper>((cartName) => new CartHelper(cartName, PrincipalInfo.CurrentPrincipal.GetContactId()));
```

And Example 2 is fixed like this:
```
c.For<Func<CultureInfo>>().Use(() => new Func<CultureInfo>(() => ContentLanguage.PreferredCulture);
```

Hope this helps someone else that has similar issues.

**Comment by jeremydmiller** [comment]
@Azazel666 If you're satisfied, would you mind closing this issue? I don't see anything here that is going to lead to any code changes. It's definitely annoying, but StructureMap is just gonna need a little help on the types when you're directly registering Func's.
