### ISSUE TITLE
Instance.Name created from MissingNamedInstanceIs should be IContext.RequestedName

### ISSUE THREAD

**Issue by DixonD-git** [structuremap/structuremap#417]
I have a scenario when I have an implementation of `IInterceptorPolicy` which has some logic dependent on `Instance.Name` which, I assume, should be set to the name of created named instances. I works fine until the instance is created by `MissingNamedInstanceIs` facility. In this case `Instance.Name` is set to random guid. Is it a bug or am I missing anything?

**Comment by jeremydmiller** [comment]
I'd guess oversight on my part;) That feature dates back to '05 or so and I haven't put much into it since. I can get around to this one by the end of the week. Plus the other issue you put in recently for that matter.

**Comment by DixonD-git** [comment]
It seems to be still reproducible if the instance is registered as `.MissingNamedInstanceIs.Type<>`. I can add a unit test later if it is needed.

**Comment by DixonD-git** [comment]
I've created a new issue https://github.com/structuremap/structuremap/issues/436 with a failing unit test
