### ISSUE TITLE
Breaking change in version 4.0.0.315

### ISSUE THREAD

**Issue by tangrl** [structuremap/structuremap#425]
I'm using Structuremap in my ASP.Net MVC 5.0 project. I upgraded Structuremap today and the project is no longer compiling. The interface  IRegistrationConvention has been changed. The old code was:

   public class ControllerConvention : IRegistrationConvention {
        #region Public Methods and Operators
        public void Process(Type type, Registry registry) {
            if (type.CanBeCastTo<Controller>() && !type.IsAbstract) {
                registry.For(type).LifecycleIs(new UniquePerRequestLifecycle());
            }
        }
        #endregion
    }

But now the interface looks like this:

 public interface IRegistrationConvention
    {
        void ScanTypes(TypeSet types, Registry registry);
    }

How  can I fix it?

Thanks!

Richard

**Comment by jeremydmiller** [comment]
@tangrl There's a description and an example of the new syntax in the docs here: http://structuremap.github.io/registration/auto-registration-and-conventions/

**Comment by jeremydmiller** [comment]
That's long enough and I'm closing.

**Comment by eddiegroves** [comment]
For anyone looking for a copy & paste fix:

```
    public class ControllerConvention : IRegistrationConvention
    {
        public void ScanTypes(TypeSet types, Registry registry)
        {
            foreach (var type in types.AllTypes())
            {
                if (type.CanBeCastTo<Controller>() && !type.IsAbstract)
                {
                    registry.For(type).LifecycleIs(new UniquePerRequestLifecycle());
                }
            }
        }
    }

```
