### ISSUE TITLE
Packet doesn't restore dependencies

### ISSUE THREAD

**Issue by jonathanfoster** [structuremap/structuremap#433]
I tried to clone the repo and build in Visual Studio, but the StructureMap.Testing project is missing references for Castle.Core, Fixie, Moq, Rhino.Mocks, and Shouldly. Packet didn't automatically restore these packages when I attempted to build the project.

**Comment by jeremydmiller** [comment]
Sigh. Just run "paket restore" from the command line. I disabled Paket's auto-restore in the csproj files because I felt it was too slow and probably failed to update readme's.

**Comment by jonathanfoster** [comment]
Would you have any issue with moving these dependencies to Nuget? I've got a PR if you want to take a look.

**Comment by jeremydmiller** [comment]
Yeah, sorry, that's absolutely a "no";) Paket's CLI and resolution is far, far better than OOTB nuget IMO. http://jeremydmiller.com/2014/06/09/final-thoughts-on-nuget/

**Comment by jonathanfoster** [comment]
Cool. Thanks for the quick response.
