### ISSUE TITLE
Unable to load assemblies from application base directory when running tests in ReSharper 

### ISSUE THREAD

**Issue by jonathanfoster** [structuremap/structuremap#435]
When running unit tests with ReSharper and NUnit3, a registry scan is unable to load assemblies from the application base directory. The same tests run from a command line successfully loads the assemblies. This is because ReSharper sets the `PrivateBinPath` to `C:\Users\{username}\AppData\Local\JetBrains\Installations\ReSharperPlatformVs14_001\NUnit3` and the `AssemblyFinder` concatenates this path with the application base directory producing an invalid path.

**Comment by jeremydmiller** [comment]
The fix for this will be in 4.1 shortly
