### ISSUE TITLE
Mvvm Memory leak in stucturemap 4

### ISSUE THREAD

**Issue by tuxado** [structuremap/structuremap#437]
I use structuremap with gmap but the structuremap dont eject thé created object proprely after creating this one by calling getinstance and saving thé object in temporary variable and ejecting thé viewmodel object and the view object from thé container by ejectobject my config is 

X.for[imap]().singleton().use[map]();

X.for[imapview]().singleton().use[mapview]();

M'y code

IMap  map = container.getinstance[IMAP]();
Container.model.for[IMAP]().défault.ejectObject();
Container.model.for[IMAPview]().défault.ejectObject();

It seem that thé container create Évry time new instance object and leak thé memory and not eject thé old object immidiately

Can have some suggestion to prevente this memory increasing that pass from 30 mo to 200 mo for only 5 consulting of thé view map

Sorry for >< and () i cant write them in coment

**Comment by jeremydmiller** [comment]
Can you try posting the code between three ticks like this:

``` csharp
var x = 0;

```

And why are you using the combination of a singleton scope, then using EjectObject() at runtime? I'd normally say that's something you should only be doing in testing code.

**Comment by tuxado** [comment]
hi,

I am new in structuremap because i use mvvm light before on wpf and i found article doing thé same mvvm partener with structuremap container as mvvm light librery i rebuild my code with structuremap but i have some view like a map view that take lot of memory space at runtime it why i eject the object map and the view after creating them with thé container  and save them to other variable to show the view  and destroy them after the view change with mvvm light i dont have this probleme on my case thé singleton not créate 1 object because thé memory increase evry time i change thé view to thé map and un thé map unload évent i destroy all variable that can increase thé memory but if style increase.. I read on some blog thar thé structuremap take some tome to distroy thé objects in cache if is true how can i destroy thèm immidiately perhabse using disposable implementation or using custom lifecycle to destroy thé object after thé get instance returne thé first object i dont know it will be  greate to add a getinstance fonction to force rebuild the singleton object an other problème with thé cache runtime i why i try to force rebuild evry time because thé canvas animation freez

**Comment by jeremydmiller** [comment]
@tuxado Hey, if you've gotten past this issue, can you close this issue? I really don't think your issue is StructureMap itself.

**Comment by tuxado** [comment]
Hello,

Yes you can close it i switch to anothee container tomporary because i detect that  when scructuremap créate an élément that i should pass some params on constructor   and then i test if this element exist in cache it tell that not exist and i cant remove it and when i try to get this élément another time it create another one perhubse i has some problèmes with thé configuration i am not sure
