### ISSUE TITLE
Lambda-created default instances do not appear to support MissingNamedInstance processing.

### ISSUE THREAD

**Issue by RichardJFoster** [structuremap/structuremap#438]
This case is based on a question originally asked at http://stackoverflow.com/questions/35089577 and which @jeremydmiller indicated was an oversight in the current processing.

Given the following registration:

```
For<ISomeInterface>().Use(() => GetConcreteInstance());
For<ISomeInterface>().MissingNamedInstanceIs.TheDefault();

For<ISomeOtherThing>().Add<OtherConcreteClass>()
    .Ctor<ISomeInterface>().IsNamedInstance("Special");
```

If no instance of ISomeInterface is subsequently registered with the name "Special" then attempting to use `[Container].GetAllInstances<ISomeOtherThing>();` will result in the following: `System.NotSupportedException: Instance's of type 'StructureMap.Pipeline.DefaultInstance' does not support ToNamedClose() and cannot be used as a MissingInstance`

The expected behavior is that the item specified using MissingNamedInstanceIs gets returned.

**Comment by jeremydmiller** [comment]
Starting on this right now.
