### ISSUE TITLE
Registries in exe not called when scanning.

### ISSUE THREAD

**Issue by jitcompile** [structuremap/structuremap#439]
I've a central library project that is used for resolving IoC calls. A container singleton is created and all calls to get instances are handled in a static method.

Naturally, this creates a problem as the calling assembly will always resolve to the library and not the actual exe.  The registry constructors in the caling exe are never called.

I've a stop gap solution where I'm getting the container singleton from my library and a 2nd scan call is made to resolve the local registries.

```
           var container = MyLibrary.GetDIContainer();

            // Scan for exe registries 
            container.Configure((expr) =>
            {
                expr.Scan(scan =>
                {
                    scan.TheCallingAssembly();
                    scan.LookForRegistries();
                    scan.WithDefaultConventions();
                });
            });
```

I was under the impression that the call to AssembliesFromApplicationBaseDirectory will include the current exe.  

I was looking at the source code and found that **FindAssemblies** method in _[AssemblyFinder.cs](https://github.com/structuremap/structuremap/blob/master/src/StructureMap.Net4/AssemblyFinder.cs)_ file looks for both dll and exe.  But uses the wrong pattern for finding exe.

```
var dllFiles = Directory.EnumerateFiles(assemblyPath, "*.dll", SearchOption.AllDirectories);
var exeFiles = Directory.EnumerateFiles(assemblyPath, "*.dll", SearchOption.AllDirectories);
```

If it was looking for ***.exe**, then the call to AssembliesFromApplicationBaseDirectory will include the current exe and the registries will automatically be resolved.

**Comment by jeremydmiller** [comment]
This is a known issue. You can explicitly add the exe assembly name in the AssemblyFinder. I will accept a pull request to make scanning for "exe" files opt in if you feel like doing it, but I don't want the exe's scanned by default because most of the time that seems to cause headaches.

**Comment by jitcompile** [comment]
Thanks @jeremydmiller for the quick response. As you said, Opt in makes more sense.  When I find free time, I'll clone the repository and see if I can create a extension method to include executables.

**Comment by jitcompile** [comment]
I've forked the repository and planning on adding the feature over the weekend.

Can you tell me how you want me to implement the same?

My idea is to add another extension method to the configuration like scan.IncludeExe() or something like that.  Split the FindAssemblies method into two - one for dll and one for exe.  Dll will be called in normal flow and exe will be called from the new method.  Is that enough or do you want to me to try something different?

**Comment by jeremydmiller** [comment]
@jitcompile I already had a pull request to add this, so I just cleaned that one up and pulled it in. There are now overloads for the AssembliesFromPath/AssembliesFromBaseDirectory() that add exe scanning in.

Closed by https://github.com/structuremap/structuremap/commit/484bec7a5007c7402275a79b1bb417705285283c
