### ISSUE TITLE
CreateChildContainer() throws System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Mike737377** [structuremap/structuremap#440]
Occasionally when calling 

> container.CreateChildContainer()

the following exception is thrown

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Add(T item)
   at StructureMap.Container.CreateChildContainer() in C:\BuildAgent\work\a395dbde6b793293\src\StructureMap.Shared\Container.cs:line 855
```

I think this might be caused by concurrency where 2 items are being added to the list at the same time and the list is not resizing correctly. Maybe _children should be of `ConcurrentBag<Container>` inside the `Container` class?

**Comment by jeremydmiller** [comment]
This was addressed in GH-444
