### ISSUE TITLE
Signed assemblies

### ISSUE THREAD

**Issue by joelweiss** [structuremap/structuremap#450]
Can you please release an update to the signed version of StructureMap 4 to [Nuget](https://www.nuget.org/packages/structuremap-signed/)?
although
> [The StructureMap team believes strong naming to be a blight upon the .Net land...](https://github.com/structuremap/structuremap/blob/76fc3c60029ce075a27bfd55b607ef0e9876ed45/documentation/get-structuremap.md#binaries)

[Prism](https://github.com/PrismLibrary/Prism) has [switched](https://github.com/PrismLibrary/Prism/issues/70) to signed assemblies and I want to upgrade to StructureMap 4

**Comment by jeremydmiller** [comment]
@joelweiss For a variety of reasons, I'm not going to be releasing any more signed versions of StructureMap. My recommendation is to try using https://github.com/dsplaisted/strongnamer to sign it on demand during the build process.

**Comment by joelweiss** [comment]
:frowning: 
I respect your decision, thanks for the quick response.

**Comment by brianlagunas** [comment]
For the record, Prism has always been strong named.  When Prism became OSS we removed the strong name signing.  This immediately broke a ton of business critical apps.  We had to immediately resign to fix the break.  Due to the maturity and adoption of Prism, we are not at a point where we can remove strong naming again.  Prism for UWP and Xamarin Forms is not strong named :)

**Comment by brianlagunas** [comment]
We actually found a good solution that should resolve this issue.  We will be updating Prism's StructureMap support to build Prism.StructureMap.Wpf.dll unsigned.  Prism.dll and Prism.Wpf.dll will still be signed.

**Comment by joelweiss** [comment]
:+1: 

@jeremydmiller  might be a good idea to update the [documentation](https://github.com/structuremap/structuremap/blob/76fc3c60029ce075a27bfd55b607ef0e9876ed45/documentation/get-structuremap.md#binaries) to reflect that signed version is no longer supported.
