### ISSUE TITLE
StructureMap could not load assembly from file

### ISSUE THREAD

**Issue by jsheldon** [structuremap/structuremap#451]
I posted this in an attempt to get a quick answer from the masses but I seemed to have stumped everyone.

http://stackoverflow.com/questions/35690528/structuremap-could-not-load-assembly-from-file-in-a-plugin-framework

Anyone have an idea on this one?  I seem to be able to load the assemblies without a problem, so I'm not sure why structuremap is flipping out.  Is there someway for me to capture the reason?

**Comment by jeremydmiller** [comment]
@jsheldon So, yes, I know why. It's trying to load the assembly by name directly from the AppDomain, which is really more efficient and less error prone than loading by the file path. Fine and good, but it should be trying to fallback to loading by the file in your case. I'm addressing this right now and it'll be in 4.1.
