### ISSUE TITLE
All StructureMap exceptions need to be marked as serializable

### ISSUE THREAD

**Issue by jeremydmiller** [structuremap/structuremap#452]

**Comment by khellang** [comment]
Just an FYI; the serializable types are going away with CoreCLR and are not available in `netstandard` TFMs :disappointed:

**Comment by jeremydmiller** [comment]
@khellang I know, but *I* need that fixed for the work I'm doing this very minute;)

**Comment by jeremydmiller** [comment]
Ah bleep it, don't wanna deal w/ all the conditional compilation crap. Live w/o the fix.

**Comment by khellang** [comment]
:stuck_out_tongue_closed_eyes:
