### ISSUE TITLE
ConfiguredInstancePolicy LifeCycle isn't as expected

### ISSUE THREAD

**Issue by ianbattersby** [structuremap/structuremap#465]
Firstly apologies if this is just me being stupid Jeremy! I have no doubts you'll tell me I am being ;)

We have a `ConfiguredInstancePolicy` for injected different instances of `IDbConnection` dependent on the ctor parameter name - a common use case no doubt. By default we configure the LifeCycle of this to `PerRequest` as we're (sadly) running under WebApi, however even with `Transient` we are getting concurrency issues with the approach I've taken, indicating that separate concurrent requests are using the same instance?!

I wonder if there is some kind of clever caching going on here I'm not appreciating?

**Usage**
```
this.Policies.Add(
        new DbConnectionPolicy(
            new Dictionary<string, Func<IDbConnection>>(StringComparer.OrdinalIgnoreCase)
                {
                    { "oneConnection", () => new SqlConnection(oneConnectionSetting.ConnectionString) },
                    { "twoConnection", () => new SqlConnection(twoConnectionSetting.ConnectionString) }
                }));
```

**Policy**
```
public class DbConnectionPolicy : ConfiguredInstancePolicy
{
    private readonly IDictionary<string, Func<IDbConnection>> connectionDictionary;

    public DbConnectionPolicy(IDictionary<string, Func<IDbConnection>> connectionDictionary)
    {
        this.connectionDictionary = connectionDictionary;
    }

    protected override void apply(Type pluginType, IConfiguredInstance instance)
    {
        var parameters = instance.Constructor.GetParameters().Where(p => p.ParameterType == typeof(IDbConnection));

        foreach (var parameter in parameters)
        {
            if (!this.connectionDictionary.ContainsKey(parameter.Name))
            {
                throw new StructureMapConfigurationException($"Contructor parameter '{parameter.Name}' on class {instance.PluggedType.FullName}' is of type IDbConnection but doesn't use our naming convention for DB connection parameters so we don't know what connection string to use for that connection instance. When taking a dependency on IDbConnection, you must use one of the following names for the ctor parameter so that we can create an appropriate IDbConnection instance: [{string.Join(", ", this.connectionDictionary.Keys)}]");
            }

            instance.Dependencies.AddForConstructorParameter(parameter, this.connectionDictionary[parameter.Name].Invoke());
            instance.SetLifecycleTo<UniquePerRequestLifecycle>();
        }
    }
}
```

*Note: StructureMap version 4.1.2.36*

**Comment by jeremydmiller** [comment]
@ianbattersby Can you check the build plan for one of the concrete types that isn't working the way you'd expect? That will force the policies to run on that registration and let us look at what's going on.

http://structuremap.github.io/diagnostics/build-plans/

**Comment by ianbattersby** [comment]
Got ya, that should have been my first port of call! _(noted)_

I don't have an default instance configured for `IDbConnection` but if I request a build-plan for the type that requires the instance created I only get the following:

```
container.Model.For<MySuperTypeNeedingInstanceOfIDbConnectionBasedOnParamName>().Default.DescribeBuildPlan()
```

```
PluginType: MySuperTypeNeedingInstanceOfIDbConnectionBasedOnParamName
Lifecycle: UniquePerRequest
new MySuperTypeNeedingInstanceOfIDbConnectionBasedOnParamName(IDbConnection)
  ┗ IDbConnection = Value: System.Data.SqlClient.SqlConnection
```

Sorry, I may need some guidance here. I will go off and experiment more later for sure!

**Comment by jeremydmiller** [comment]
The build plan sure looks to me like the policy is working correctly. You're setting the lifecycle just fine.

When you add the dependency for the SqlConnection, are you registering that as a Lambda, or is it using the same SqlConnection for all instances? Looks like it's the 2nd to me. Your problem might be on the connection, not the SM lifecycle

**Comment by ianbattersby** [comment]
So the Invoke on the Func won't create a new one for each instance created? I need to make the param itself a Func? I hadn't anticipated that!

**Comment by ianbattersby** [comment]
Hey Jeremy, can you confirm is passing a `Func<IDbConnection>` into the `ConfiguredInstancePolicy` and calling `Invoke()` from within there when creating the instance is _not sufficient_? I feel that should have worked but likely missing something knowledge-wise :(

**Comment by jeremydmiller** [comment]
You need to invoke the lambda at the time each instance is created, but you're doing it at the time the policy is executed, and de facto making the underlying dependency be shared. I'll post the syntax for that when I get back to my computer

**Comment by jeremydmiller** [comment]
@ianbattersby,

Try changing:

```
instance.Dependencies.AddForConstructorParameter(parameter, this.connectionDictionary[parameter.Name].Invoke());
```

to

```
var conn = new LambdaInstance<IDbConnection>("use your key here for diagnostics", this.connectionDictionary[parameter.Name]);
instance.Dependencies.AddForConstructorParameter(parameter, conn);
```

**Comment by ianbattersby** [comment]
Thanks so much! We'll give this a good go and report back :)

**Comment by ianbattersby** [comment]
Ah my bad, we fixed the code but never tried it in favour of our hack. Will chase up!
