### ISSUE TITLE
Child containers don't inherit family policies from their parent

### ISSUE THREAD

**Issue by saquibmian** [structuremap/structuremap#469]
We're in the middle of upgrading from SM 2 to 4. I'm running into a case where open generics don't work for child containers, and I'm not sure if this is a bug or is expected behaviour. 

I have the following class and interface:

```csharp
public interface IOpenGeneric<T> { }
public sealed class OpenGeneric<T> : IOpenGeneric<T> {
	public OpenGeneric() { }
}
```

Here are the tests I'm running:

```csharp
[Test]
public void OpenGenericTest1() {
	IContainer container = new Container();

	container.Configure( x => {
		x.For( typeof( IOpenGeneric<> ) )
			.Use( typeof( OpenGeneric<> ) )
			.LifecycleIs<ThreadLocalStorageLifecycle>();
	} );

	var obj = container.GetInstance<IOpenGeneric<string>>();
	
	// this passes
	Assert.IsNotNull( obj );
}

[Test]
public void OpenGenericTest2() {
	IContainer container = new Container().CreateChildContainer();

	container.Configure( x => {
		// if I uncomment this, the test passes
		// x.Configure( g => g.AddFamilyPolicy( new CloseGenericFamilyPolicy( g ) ) );
		x.For( typeof( IOpenGeneric<> ) )
			.Use( typeof( OpenGeneric<> ) )
			.LifecycleIs<ThreadLocalStorageLifecycle>();
	} );

	var obj = container.GetInstance<IOpenGeneric<string>>();
	
	// this fails
	Assert.IsNotNull( obj );
}
```

Digging through a code a little shows that `PluginGraphBuilder`'s `Build` method calls `addCloseGenericPolicyTo` when creating the root `PluginGraph`, but that on child containers the `PluginGraphBuilder` is not used -- instead `new PluginGraph` is used.

**Comment by jeremydmiller** [comment]
@saquibmian It's not something that I ever *intended* work, no. Is it really necessary to make that registration on the child container? Would it help to just register this with the parent, but then use the new "Container" lifecycle to isolate it to the child container.

Also, why is the ThreadLocal storage necessary in your application? That's generally a legacy approach now.

**Comment by saquibmian** [comment]
@jeremydmiller Unfortunately, yes. The use case around these child registrations is that our HTTP pipeline will create a child container for each web request and register some context-aware objects with it -- other objects can depend on those context objects within the scope of that web request. (I know technically nested containers are better suited for a web request scenario, but for legacy reasons we can't use those yet (because nested containers are stricter with what lifecycles can be used for their registrations).)

The `ThreadLocal` lifecycle is to support a legacy workflow. I'll be working to strip some of that away after I can get the upgrade working, so that it's not such a significant change all at once.

**Comment by jeremydmiller** [comment]
I could maybe be talked into supporting the open generic policy in the child containers, but first, is there any way you could just "explode" out the registrations to begin with? That'd be more efficient at runtime anyway.

**Comment by jeremydmiller** [comment]
Haven't heard any update here. I'm closing this one.
