### ISSUE TITLE
can't automocking my class

### ISSUE THREAD

**Issue by arielcloud** [structuremap/structuremap#472]
my class is like:

      public class BillingAccountBLService : IBillingAccountBLService
      {
        [SetterProperty]
        public IContractService ContractService { get; set; }

        public BillingAccountBLService()
        {
            ObjectFactory.BuildUp(this);
         }
       }

in my test:

     [Test]
        public void ContractDoesNotExist()
        {
            var mocks = new RhinoAutoMocker<BillingAccountBLService>();
            var service = mocks.ClassUnderTest;
            ...
   `
on this row exception thrown "StructureMap.StructureMapConfigurationException : No default Instance is registered and cannot be automatically determined for type..." (type of first injected service)

how should i fix this?

thanks!

**Comment by jeremydmiller** [comment]
@arielcloud Sorry I missed this for so long. Try removing the call to ObjectFactory.BuildUp() in the constructor. That would be defeating your auto mocker. And I'd recommend constructor injection anyway.
