### ISSUE TITLE
Nested container doesn't honor parent container registration as a singleton if parent container is a child container

### ISSUE THREAD

**Issue by cholt0425** [structuremap/structuremap#473]
One note is I am still on StructureMap 3
```c#
var container = rootContainer.CreateChildContainer();
container.Configure(c =>
                {
                    c.ForSingletonOf<Widget>();
                });

var instance1 = container.GetInstance<Widget>();

var nestedContainer = container.GetNestedContainer();

var instance2 = nestedContainer.GetInstance<Widget>();

Assert.IsSame(instance1, instance2);
```

**Comment by cholt0425** [comment]
I found the offending code in Container.cs.  I guess the question now is why does this do this?

```
/// <summary>
        ///     Used to add additional configuration to a Container *after* the initialization.
        /// </summary>
        /// <param name="configure"></param>
        public void Configure(Action<ConfigurationExpression> configure)
        {
            lock (_syncLock)
            {
                _pipelineGraph.Configure(configure);

                // Correct the Singleton lifecycle for child containers
                if (Role == ContainerRole.ProfileOrChild)
                {
                    var singletons = _pipelineGraph.Instances.ImmediateInstances()
                        .Where(x => x.Lifecycle is SingletonLifecycle);

                    singletons
                        .Each(x => x.SetLifecycleTo<ContainerLifecycle>());

                    _pipelineGraph.Instances.ImmediatePluginGraph.Families.Where(x => x.Lifecycle is SingletonLifecycle)
                        .Each(x => x.SetLifecycleTo<ContainerLifecycle>());
                }


                if (Role == ContainerRole.Nested)
                {
                    _pipelineGraph.ValidateValidNestedScoping();
                }
            }
        }
```

**Comment by jeremydmiller** [comment]
You're talking about this:                     

```

                   var singletons = _pipelineGraph.Instances.ImmediateInstances()
                        .Where(x => x.Lifecycle is SingletonLifecycle);

                    singletons
                        .Each(x => x.SetLifecycleTo<ContainerLifecycle>());
```

In the 3.0 timeframe, "Singleton" made it go all the way to the top of the root container and made it resolve from the root container, so registering something to a child container as a singleton didn't work. I fixed that by making a new "container" lifecycle that would correct the scoping to resolve from the first "not a nested container" parent. 

Great, but in 4.0 the "container" lifecycle was changed a bit to conform to what the ASP.Net team says container must do so that container scoped means "to a particular container", whether that be the root or a nested container. *That* change broke the "singleton registered to a child container" workaround from 3 and that's where you're at right now.

**Comment by cholt0425** [comment]
Are you saying that if I move to 4.0 that my code in the first post will work as I expect it to?

**Comment by cholt0425** [comment]
Added unit test pull request to test scenario.  Currently it fails.  I can try to figure out a fix but I'm not sure it is worth while since I am on version 3 and the current version is 4.  I would upgrade to 4 but I need a signed version and I don't have the time to add signing back into the build as an option.

**Comment by jeremydmiller** [comment]
@cholt0425 Have you tried StrongNamer? Sorry, but I'm very unlikely to either go back to pushing out a signed assembly or make a fix this involved on the 3.1.* branch.

**Comment by cholt0425** [comment]
@jeremydmiller No, I have never heard of that.  I'll look into it.  If someone else ends up fixing the bug in 4.0 then I'll review it and see if I can integrate it into the branch I have of 3.x or at least into the latest release of 3.x.

**Comment by jeremydmiller** [comment]
I think what I'm saying is that I would be willing to address the bug in a 4.* release. That work hasn't happened yet.

**Comment by cholt0425** [comment]
@jeremydmiller That StrongNamer seems promising...Thanks for the pointer to it!

**Comment by jeremydmiller** [comment]
@cholt0425 This had been previously addressed in the 4.* codebase, but I added your test as well.

**Comment by cholt0425** [comment]
@jeremydmiller Thanks!
