### ISSUE TITLE
The default assembly when scan WithDefaultConventions

### ISSUE THREAD

**Issue by SummerSun** [structuremap/structuremap#477]
Reading the official doc, WithDefaultConventions seems always be called along with code finding specific assemblys:
```C#
_.AssemblyContainingType<IInterface>();
_.TheCallingAssembly();
```
If, just this:
```C#
 Scan(_ =>  { _.WithDefaultConventions(); });
```
What assembly will it scan? Is there any default assembly in design, or should there be?

I tried it but seems WhatDoIHave returns nothing related the calling assembly with this single line of code.

**Comment by jeremydmiller** [comment]
There's no magic going on under the covers, you have to specify the assembly or assemblies you want that particular `Scan()` operation to apply to.

From the docs at http://structuremap.github.io/registration/auto-registration-and-conventions/: 


Any given call to Registry.Scan() consists of three different things:

1. One or more assemblies to scan for types
1. One or more registration conventions
1. Optionally, set filters to only include certain types or exclude other types from being processed by the scanning operation

**Comment by SummerSun** [comment]
Thank you Jeremy for both the answer and the link of asking question. 
Actually, another reason for raising a GitHub issue here is that I am wondering, could it make more sense if there is some magic under the default conventions, say set the calling assembly as default?
Anyway, thank you for the quick reply.
