### ISSUE TITLE
Disordered page http://structuremap.github.io/

### ISSUE THREAD

**Issue by SummerSun** [structuremap/structuremap#481]
Checking the documentation but notice that the style in the main page http://structuremap.github.io/ is disordered.
![image](https://cloud.githubusercontent.com/assets/5179063/16182397/396da210-36d8-11e6-9bc9-997ef76e7388.png)

Request URL:https://camo.githubusercontent.com/da2edb525cde1455a622c58c0effc3a90b9a181c/68747470733a2f2f6261646765732e6769747465722e696d2f4a6f696e253230436861742e737667
Request Method:GET
Status Code:**404 Not Found**
Remote Address:103.245.222.133:443

**Comment by jeremydmiller** [comment]
Dunno what to tell you, it's fine on my box w/ Chrome, IE, and Safari.
