### ISSUE TITLE
ASP.NET Core RTM compatible Nuget?

### ISSUE THREAD

**Issue by joeaudette** [structuremap/structuremap#484]
Any idea when we can expect an updated nuget compatible with ASP.NET Core RTM?
Trying to update another project and blocked on this.

**Comment by jeremydmiller** [comment]
@joeaudette SM has supported CoreCLR for quite a while. Is there something about RTM that blocks SM usage?

**Comment by joeaudette** [comment]
@jeremydmiller sorry, I'm trying to update the [saaskit project](https://github.com/saaskit/saaskit) to ASP.NET Core RTM and I got it all working except the [StructureMap Sample](https://github.com/saaskit/saaskit/tree/master/samples/AspNetStructureMapSample), it compiles but it gives an error at runtime so I assumed that the StructureMap nuget wasn't compatible, though it does build fine. If you say it should workthan probably it was a false assumption and something else is causing the runtime error. I will dig deeper

**Comment by jeremydmiller** [comment]
Got a stacktrace? What version are you using?

**Comment by joeaudette** [comment]
my bad, it is working now, sorry for the trouble

**Comment by jeremydmiller** [comment]
Whew.

**Comment by joeaudette** [comment]
sorry for the false alarm
