### ISSUE TITLE
Why does a dynamic lookup (runtime GetInstance) always result in a lambda compilation?

### ISSUE THREAD

**Issue by NinoFloris** [structuremap/structuremap#486]
This is the first load, and seems to build a buildplan for this specific type as you would expect:
![slow](https://cloud.githubusercontent.com/assets/4218809/16453885/bfd16bf6-3e0e-11e6-9370-d37c147c72b8.png)

And this is a future iteration (don't mind the handle call, this steps into an async op that get's shuffled to another thread by the CLR while it was run sync the first time, explaining the gap from 53 ms to 1.4ms):
![fast](https://cloud.githubusercontent.com/assets/4218809/16453494/4d307070-3e0d-11e6-8d0e-934c78bee6a5.png)

Why is there any need to recreate (+ compile and thus jit) a lambda expression from the build plan? As it will get used only once. I would have guessed this to be not as slow as the profiler shows it is.

We have a container -> child container -> per request (nested) container structure.
All the constructor arguments are transient.

Just trying to understand the process here, we are optimizing our performance on all fronts and this is no exception.

**Comment by jeremydmiller** [comment]
"Why is there any need to recreate (+ compile and thus jit) a lambda expression from the build plan?" - there isn't any need, and StructureMap itself caches the build plan Func on the first usage of any `Instance`. See this code for a reference: https://github.com/structuremap/structuremap/blob/master/src/StructureMap.Shared/Pipeline/Instance.cs#L121-L127

My question is whether or not you're really seeing StructureMap have to generate the build plan more than once for a unique Instance?

**Comment by NinoFloris** [comment]
MediatR does no injection, all its handlers are attached at startup. The only thing I can imagine is that the nested container itself is in the way of caching this build plan, as we use MediatR to connect controller actions to MediatR handlers so this is only called once per request. 

This is the definition that is run at startup (root container), not after nested container creation.
```cs
For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => ctx.GetInstance(t));
For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => ctx.GetAllInstances(t));
For<IMediator>().Use<Mediator>();
```

I have seen this penalty on each request that I fired and it showed in the timeline.
But take note that the plan at least drastically speeds up after the first run (4.6 ms vs 20ms).

**Comment by jeremydmiller** [comment]
@NinoFloris Any chance you could put together some kind of code that demonstrates the issue? What you're describing isn't how SM normally behaves. My theory is that *something* in your codebase is causing it to make a new Instance registration on each request so that StructureMap treats it as something all new.

You could verify that if you see a different Id on the Instance when it calls buildPlan().
