### ISSUE TITLE
NETStandard 1.6 Support

### ISSUE THREAD

**Issue by cemremengu** [structuremap/structuremap#489]
Currently trying to adapt structure map 4.2.0.402 for a project dependent on net standard 1.6 but seems like it is not compatible yet. 

Is there a work around for this ? Or anything on the roadmap ?

**Comment by jeremydmiller** [comment]
I know the nuget doesn’t say that it targets Netstandard, but you should be able to use it as is. Other folks have been able to use SM 4+ with CoreCLR projects.

**Comment by cemremengu** [comment]
I am getting an error during package restore / build though :(

Tried importing ` portable-net45+win81+wp81` but still couldnt get it to work.

`error: Package StructureMap 4.2.0.402 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package StructureMap 4.2.0.402 supports:
error:   - dotnet (.NETPlatform,Version=v5.0)
error:   - net40 (.NETFramework,Version=v4.0)
error:   - portable-net40+win8+wp8 (.NETPortable,Version=v0.0,Profile=net40+wp8+win8)
error:   - portable-net45+win81+wp81 (.NETPortable,Version=v0.0,Profile=net45+wp81+win81)
error: One or more packages are incompatible with .NETStandard,Version=v1.6.`

**Comment by jeremydmiller** [comment]
I don't know. How are you trying to install it? New world order stuff? 

I'm not going to be able to do anything until the end of next week to address it. I really don't want to stop and try to convert to project.json until I have more time.

**Comment by cemremengu** [comment]
Not really 😄  fair enough, I may take a look as well if I have time

**Comment by khellang** [comment]
This works fine; https://github.com/khellang/nancy-bootstrapper-prototype/blob/master/src/Nancy.Bootstrappers.StructureMap/project.json

**Comment by cemremengu** [comment]
@khellang thanks that fixed it
