### ISSUE TITLE
Exception when calling TryGetInstance<T> with empty string or null

### ISSUE THREAD

**Issue by knoxi** [structuremap/structuremap#491]
We updated to StructureMap V4 and when we call `TryGetInstance<T>` with an empty name, we get an ArgumentException or an ArgumentNullException when the name is null.

Sample:
`   var instance = container.GetProfile("A").TryGetInstance<IType>("");`

In V3.1.5 there was no exception for this call.

My understanding of methods or functions which begins with `TryGet...()` is, that they don't throw an exception but returns null for the requested type. The exceptions would be ok when calling the `Get...()` methods.

**Comment by jeremydmiller** [comment]
That is expected behavior for that overload. Use the overload that doesn't have any args to do a TryGetInstance against the default registration. What you're trying to do is fetch a named instance, so yeah, it blows up when the name is null or blank;)
