### ISSUE TITLE
Reuse build plan across matching calls to With() resolution w/ explicit arguments

### ISSUE THREAD

**Issue by jeremydmiller** [structuremap/structuremap#494]
Having to constantly re-compile the Lambda delegates is hurting fubumvc perf.

**Comment by leddt** [comment]
@jeremydmiller I believe this was a breaking change. The following test fails in StructureMap 4.3 (as well as the latest 4.4.3), but passes in 4.2.0.402. 

If I mark `SomeClass` as `AlwaysUnique`, then the test passes in all versions. Note also that the test passes for a _regular_ container. It only fails on _nested_ containers.

```csharp
[TestFixture]
public class StructureMapTest
{
    [Test]
    public void GetDifferentInstanceBetweenCalls()
    {
        var container = new Container().GetNestedContainer();

        var i1 = container.With(new object()).GetInstance<SomeClass>();
        var i2 = container.With(new object()).GetInstance<SomeClass>();

        Assert.That(i1, Is.Not.SameAs(i2));
    }
}

public class SomeClass
{
    public object Config { get; }

    public SomeClass(object config)
    {
        Config = config;
    }
}
```

**Comment by jeremydmiller** [comment]
@leddt Can you just start a new issue for this? Interested in doing a PR for it? Might be as simple as making the `ExplicitInstance` have the always unique lifecycle.
