### ISSUE TITLE
Disposing of Transient objects in the root container (when setting it via configure)

### ISSUE THREAD

**Issue by dbones** [structuremap/structuremap#500]
When setting Transient Tracking to explicit, it only works if applied on the ctor, not if it is set via configure.

Configure (only disposes of transient objects on child and nested containers, not the base/root container)

```
using (var container = new StructureMap.Container())
    {
        container.Configure(cfg =>
        {
            cfg.TransientTracking = TransientTracking.ExplicitReleaseMode;
```

this works

```
using (var container = new StructureMap.Container(_ => _.TransientTracking = TransientTracking.ExplicitReleaseMode))
```

please refer to this post post for more information:
https://groups.google.com/forum/#!topic/structuremap-users/bGCkh4LIBhE

**Comment by jeremydmiller** [comment]
@dbones I really don't recommend this usage anyway. It's only there to satisfy the new ASP.Net Core IoC abstraction requirements.

My response is to just set that when you create the container. `Container.Configure()` is potentially expensive, so you try to avoid using that very much anyway.

**Comment by dbones** [comment]
that is fine, I know how to set this up the other way.

you may want to put a note in the docs if you do not fix it. So others do not think they have done something wrong. 

or if possible remove it as an option in the configure method.
