### ISSUE TITLE
StructureMap reuses instances when using factories and named objects

### ISSUE THREAD

**Issue by ramondeklein** [structuremap/structuremap#504]
I have some issues when using named objects that are created via factory. I have defined the following interface:

    public interface ISayHello
    {
        void SayHello();
    }

And the following implementation:

    public class SayHelloImpl : ISayHello
    {
        private readonly Guid _id = Guid.NewGuid();
        public void SayHello() => Console.WriteLine($"Hello {_id}");
    }

I have registered this interface like this:

    new Container(c => c.For<ISayHello>().Add<SayHelloImpl>().Named("A"))

When I invoke two instances like this:

    container.GetInstance<ISayHello>("A").SayHello();
    container.GetInstance<ISayHello>("A").SayHello();

Then two different identifiers are printed. Just the way I would expect. But when I obtain a factory that can create instances, then it seems to re-use the objects:

    var sayHelloFactory = container.GetInstance<Func<string, ISayHello>>();
    sayHelloFactory("A").SayHello();
    sayHelloFactory("A").SayHello();

This prints the same identifier twice. I wouldn't expect this behaviour.

See also [this gist](https://gist.github.com/ramondeklein/ca9fa880364411a48ae220a138f16eba) for a reproduction scenario.

**Comment by jeremydmiller** [comment]
@ramondeklein This is working as designed. The Func<T> is built against the original "build session" of whatever you resolved it with. Func<T> was originally meant to be what Lazy<T> is now in SM.

The quickest thing for you to get what I think you want here is:

```
new Container(c => c.For<ISayHello>().Add<SayHelloImpl>().Named("A").AlwaysUnique())
```

**Comment by ramondeklein** [comment]
Not what I expected, but `AlwaysUnique()` seems to solve the issue.
