### ISSUE TITLE
Very slow performance when configuring Container

### ISSUE THREAD

**Issue by shaulbehr** [structuremap/structuremap#505]
Today I was investigating slowness in our system. By inserting some debug logs, I narrowed it down to this segment:
```
var db = MyDbContext.ForShard(shardKey);
_logger.Debug("Point 1");
container.Configure(cfg =>
                    {
                        _logger.Debug("Anon 1");
                        cfg.For<MyDbContext>().Use(db);
                        _logger.Debug("Anon 2");
                    });
_logger.Debug("Point 2");
```
The database is sharded, and shardKey identifies which shard to use. The call to MyDbContext.ForShard() returns a database connection whose connection string refers to the correct shard. The snippet in question then tells the StructureMap Container to use this instance for dependency injection.

In the logs, the time lag between each line is negligible, except for the gap between "Anon 2" and "Point 2", which can take in the region of a second. Not good. But I've never seen StructureMap taking so long to configure a usage.

Am I doing something wrong here?

**Comment by khellang** [comment]
What version of SM are you using? Is this something that you've been seeing for a while or something that just started happening?

**Comment by CoreyKaylor** [comment]
The configure call shouldn't happen during runtime, only startup so if this call is happening for every web request as an example it would be extremely slow as the configure call requires a global lock. A better alternative if you absolutely need runtime overrides is to use a nested container for the scope of an http request and pass TypeArguments to the nested container. That's all assuming you're running the latest version of StructureMap too.

**Comment by shaulbehr** [comment]
@khellang I upgraded to the latest (4.4.0) and this didn't help.  I can't say how long this has been happening; the system has been in dev for a long time, and only now the QAs are giving it a go and complaining that it's slow.

@CoreyKaylor Thanks, that's useful info.  I don't really have much choice in this particular code path, since it's in the login method, and we don't know which db connection to use until we've authenticated the user.  When you say "use a nested container for the scope of an http request and pass TypeArguments to the nested container", what exactly does that mean?  Can you please give me an example?

Thanks for your super-quick responses!

**Comment by CoreyKaylor** [comment]
This covers the nested container topic much better than I could elaborate in a short reply.

http://structuremap.github.io/the-container/nested-containers/

If a nested container isn't an option

http://structuremap.github.io/resolving/passing-arguments-at-runtime/

An example of usage in FubuMVC.

https://github.com/DarthFubuMVC/fubumvc/blob/master/src/FubuMVC.Core/StructureMap/NestedStructureMapContainerBehavior.cs

**Comment by khellang** [comment]
@shaulbehr Someone mentioned that the 4.4 package has debug-built assemblies. Might want to change to a different version when measuring.

**Comment by jeremydmiller** [comment]
@shaulbehr I'm rushing out a StructureMap 4.4.1 package that fixes the accidental "Debug" nuget. For your exact usage, there's a huge performance optimization in 4.4. Use:

```
var nested = container.GetNestedContainer(TypeArguments);
```

where TypeArguments holds the defaults you want injected into your nested container by type. We hit the exact same issue in our own usage and this was how we addressed it. `Container.Configure()` is pretty heavyweight and should be avoided as much as possible at runtime.

**Comment by jeremydmiller** [comment]
4.4.1 is up and compiled to Release.

**Comment by shaulbehr** [comment]
OMG you guys move fast.
I'll try it out tomorrow.
Thanks so much!

**Comment by shaulbehr** [comment]
Yup, problem solved.  Thanks for your amazing support!
