### ISSUE TITLE
Unexpected setter injection

### ISSUE THREAD

**Issue by e-tobi** [structuremap/structuremap#509]
Configuring a Ctor<> argument causes all public properties of that type to be injected as well:

    [TestFixture]
    public class UnexpectedSetterInjection
    {
        [Test]
        public void Should_not_inject_a_setter()
        {
            using (var container = new Container(c =>
            {
                c.For<Foo>().Use<Foo>().Ctor<Bar>("bar1").Is<Bar>();
            }))
            {
                var foo = container.GetInstance<Foo>();
                Assert.That(foo.Bar1, Is.Not.Null);
                Assert.That(foo.Bar2, Is.Null); // fails!
            }
        }

        public class Foo
        {
            public Foo(Bar bar1)
            {
                Bar1 = bar1;
            }

            public Bar Bar1 { get; private set; }
            public Bar Bar2 { get; set; }
        }

        public class Bar
        {
        }
    }

I think this was already discussed here: https://groups.google.com/forum/#!topic/structuremap-users/4wA737fnRdw

...but I really think this is a serious issue. The documentation states:

> In all cases, Setter Injection is an opt-in feature in StructureMap that has to be explicitly enabled on a case by case basis.

So its absolutely not expected to have a setter injection happenning in the above example if you choose to explicitly inject something via the constructor and even specify the ctor argument name.

**Comment by jeremydmiller** [comment]
@e-tobi I'll give you the same response I've given every time this has come up. It's too much work to change this underlying behavior and extremely easy to work around. **Everything** works easiest if you'll just go with pure constructor injection and I feel like this is a rare edge case.

**Comment by e-tobi** [comment]
I don't think this is a rare edge case. Sometimes you simply have some properties with a public setter of the same type as a ctor argument. This is especially true for types like string, int and so on.
There should at least be a big fat warning in the documention about this unexpected side effect.

I think this happens a lot more often than you think and people just do not notice. I only stumbled upon this while debugging and seeing two allocations of the same class where I expected only one.

**Comment by jeremydmiller** [comment]
@e-tobi Put in the pull request then. The best practices part of the StructureMap documentation urges against injecting primitives anyway.
