### ISSUE TITLE
Possible concurrency issue in StructureMap.Util.Cache, version 3.1.6

### ISSUE THREAD

**Issue by erik-kallen** [structuremap/structuremap#512]
Hi, I am investigating a very strange issue in our production environment, and this led me to check the StructureMap.Util.Cache class (https://github.com/structuremap/structuremap/blob/1075e6f49a8b9b15aa86e16bf4a15425421e2450/src/StructureMap/Util/Cache.cs)

Most of the methods will take the lock represented by `_rwLock`, but the indexer and the `GetEnumerator()` implementations will not (and if the indexer did take it, `GetValue()` takes the lock twice in succession so it is not atomic).

Is this an issue? Looks like it to me.

**Comment by jeremydmiller** [comment]
That all went away if you move up to StructureMap 4.*.

**Comment by erik-kallen** [comment]
Unfortunately we are stuck with version 3 due to dependencies

**Comment by jeremydmiller** [comment]
If you want, I can take a pull request to the 3.1 branch and push another update:https://github.com/structuremap/structuremap/commits/3.1

In 4, the `Cache` class was completely replaced with `ConcurrentDictionary`. You could repeat that change.

**Comment by erik-kallen** [comment]
So you think it is possible to backport the ```Cache``` to ```ConcurrentDictionary``` change to 3.1? If so, I can look into that tomorrow

**Comment by jeremydmiller** [comment]
This was done.
