### ISSUE TITLE
Unable to replace a parameter at runtime

### ISSUE THREAD

**Issue by silkfire** [structuremap/structuremap#519]
I'm trying to override a constructor parameter, namely a Uri, at runtime but so far have been unsuccessful.

Registration:

```
Container = new Container(_ =>
            {
                _.ForConcreteType<RestClient>()
                 .Configure
                 .Ctor<string>("userAgent")
                 .Is(() => config["RestClientUserAgent"])
                 .Ctor<Uri>("uri")
                 .Is(() => new Uri("http://www.google.com"));
            });
```

Invocation:

```
var rc1 = Startup.Container.With("uri").EqualTo(new Uri("https://www.amazon.com")).GetInstance<RestClient>();
```

I get an instance of RestClient successfully, but unfortunately, the BaseUri of the instance remains "http://www.google.com" as per the registration. Strangely enough, if I do the same thing, but for the "userAgent" parameter, I have no problem changing it.

Is this some kind of bug?

**Comment by jeremydmiller** [comment]
Dunno, it's nothing I've ever tried to do. Can you try With<Uri>( uri ) instead?

**Comment by silkfire** [comment]
That still didn't work. It's as if the resolver doesn't want to replace the initially assigned constructor parameter. Only works for the string parameter, though....

**Comment by jeremydmiller** [comment]
Can you add a failing test here that describes what you're trying to do that's not working and I'll take a look at that on Monday?

**Comment by silkfire** [comment]
I'm trying to override a constructor argument defined in the container registration, as specified here: http://structuremap.github.io/resolving/passing-arguments-at-runtime/

> _The canonical usage is overriding file paths, database connection string, or urls._

It seems to work with one of the arguments, but not the other one.

```
var container = new Container(_ =>
{
    _.ForConcreteType<RestClient>()
      .Configure
      .Ctor<Uri>("baseUrl")
      .Is(new Uri("http://www.google.com"));
});

using (var nested = container.GetNestedContainer())
{
    var rc = nested.With("baseUrl").EqualTo(new Uri("http://www.amazon.com")).GetInstance<RestClient>();

   // In this instance, BaseUrl is still "http://www.google.com"
}
```

I'm using RestSharp.NetCore as the RestClient.

**Comment by silkfire** [comment]
Hi Jeremy,

Any update on this issue?

**Comment by jeremydmiller** [comment]
@silkfire I'm looking at it now.

**Comment by jeremydmiller** [comment]
@silkfire This code worked for me in SM 4.4:

```

        public class RestClient
        {
            public string UserAgent { get; set; }
            public Uri Uri { get; set; }

            public RestClient(string userAgent, Uri uri)
            {
                UserAgent = userAgent;
                Uri = uri;
            }
        }

        [Fact]
        public void can_use_uri_as_explicit_argument()
        {
            var originalUri = new Uri("something://1");

            var container = new Container(_ =>
            {
                
                _.ForConcreteType<RestClient>()
                    .Configure
                    .Ctor<string>("userAgent").Is("Original")
                    .Ctor<Uri>().Is(originalUri);
            });

            var original = container.GetInstance<RestClient>();

            original.Uri.ShouldBe(originalUri);
            original.UserAgent.ShouldBe("Original");

            var overridden =
                container.With<Uri>(new Uri("something://2"))
                    .With("userAgent")
                    .EqualTo("Different")
                    .GetInstance<RestClient>();

            overridden.UserAgent.ShouldBe("Different");
            overridden.Uri.ShouldBe(new Uri("something://2"));
        }
```

**Comment by silkfire** [comment]
Your code works for me as well. Then thing is, it only works with a single `With<Uri>(new Uri("something://2")`, but not if I supply the parameter name as a string: `With("uri").EqualTo(new Uri("something://2"))`.

Also, it seems in some cases I need `AlwaysUnique()`. Are concrete types not transient in StructureMap?

**Comment by jeremydmiller** [comment]
Concrete types are transient. You can see the rules on what that actually means in StructureMap here: http://structuremap.github.io/object-lifecycle/

**Comment by jeremydmiller** [comment]
Dude, can you send me an exact unit test that fails to reproduce your problem? I still don't get what's not working for you here.

**Comment by silkfire** [comment]
Sorry, was't my intention being rude. I've just been annoyed with this for a while. I definitely know it's not your fault.

Here's a unit test you can try to run. Both tests fail.

```
namespace PostNordTrackCore.Test
{
    using StructureMap;
    using Xunit;

    using System;
    

    public class UnitTest1
    {
        [Fact]
        public void restclient_uri_should_not_be_null()
        {
            var container = new Container(_ =>
            {
                _.ForConcreteType<RestClientTest>()
                 .Configure
                 .Ctor<string>("userAgent")
                 .Is(() => "UA")
                 .Ctor<Uri>("uri")
                 .Is(() => null);
            });


            var rc = container.With("uri").EqualTo(new Uri("http://www.google.com")).GetInstance<RestClientTest>();

            Assert.NotNull(rc.Uri);
        }

        [Fact]
        public void restclient_uris_should_be_different()
        {
            var container = new Container(_ =>
            {
                _.ForConcreteType<RestClientTest>()
                 .Configure
                 .Ctor<string>("userAgent")
                 .Is(() => "UA")
                 .Ctor<Uri>("uri")
                 .Is(() => null);
            });


            var rc1 = container.With("uri").EqualTo(new Uri("http://www.google.com")).GetInstance<RestClientTest>();
            var rc2 = container.With("uri").EqualTo(new Uri("http://www.amazon.com")).GetInstance<RestClientTest>();

            Assert.True(rc1.Uri.AbsoluteUri != rc2.Uri.AbsoluteUri);
        }
    }


    public class RestClientTest
    {
        public string UserAgent { get; set; }
        public Uri Uri { get; set; }

        public RestClientTest(string userAgent, Uri uri)
        {
            UserAgent = userAgent;
            Uri = uri;
        }
    }
}
```

**Comment by jeremydmiller** [comment]
@silkfire I'm **finally** looking at this now.

**Comment by jeremydmiller** [comment]
@silkfire This will be in the next nuget (4.4.3 or 4.5, not sure yet). It didn't have anything to do with the `Uri` type. SM was still giving preference to the original inline dependency instead of overriding the choice. I addressed that.

**However**, I know this is counter intuitive, but it would be much more efficient inside of StructureMap to use a parameter object like below:

```
public class RestUri
{
    public Uri Uri {get;set;}
    public string UserAgent {get;set;}
}
```

Then do your `With()` using the `RestUri` class. You're creating an extra object, but you're allowing StructureMap to reuse the "build plan" for the `RestClient`, which it can't if you have a primitive argument like the user agent string.
