### ISSUE TITLE
Assembly scanning not working when targeting .NET Core app

### ISSUE THREAD

**Issue by amattie** [structuremap/structuremap#522]
In StructureMap 4.4.1, I can't get any of `IAssemblyScanner`'s path or directory scanning operations to work in my app that targets `netcoreapp1.1`. Pretty certain it didn't work with 1.0 either.

After poking around a bit, I think the problem is that the wrong conditional compilation symbols are used in [TypeExtensions.cs](https://github.com/structuremap/structuremap/blob/94b2e351cd1b232678248e21fd17a4f5167eac34/src/StructureMap/TypeExtensions.cs) and [AssemblyFinder.cs](https://github.com/structuremap/structuremap/blob/94b2e351cd1b232678248e21fd17a4f5167eac34/src/StructureMap/Graph/AssemblyFinder.cs). The [multi-targeting docs](https://github.com/dotnet/docs/blob/b0f0eb6c9de509d96dda18744005431621f77bbf/docs/core/tutorials/libraries.md#how-to-multitarget) say that `NETSTANDARD1_3` and `NETSTANDARD1_5` should be used, but the aforementioned files target `NETSTANDARD13` and `NETSTANDARD15`.

When I change those files to use the documented compilation symbols, path scanning is fixed.

**Comment by jeremydmiller** [comment]
Nice. Feel like doing a pull request for this?

**Comment by jeremydmiller** [comment]
Closed by #523
