### ISSUE TITLE
How to decorate scanned ConnectImplementationsToTypesClosing types?

### ISSUE THREAD

**Issue by NinoFloris** [structuremap/structuremap#525]
Ok so after trying many different ways of getting this to work I'm coming here, I've given up.

How would I decorate a generic interface type that has 20+ implementations with 5 to 6 decorators?

So that every GetInstance call for a closed version of this generic interface type results in a 'pipeline' of these decorators + the final real implementation.

**Comment by jeremydmiller** [comment]
"How would I decorate a generic interface type that has 20+ implementations with 5 to 6 decorators?" -- I would strongly suggest that you don't do that because of the complexity. Just curious, why do you want to do this? This isn't related to MediatR is it?


There's an example of applying an interception policy to an open generic interface in the docs at the very bottom of this page:

http://structuremap.github.io/generics/

Does that help at all?

**Comment by NinoFloris** [comment]
> This isn't related to MediatR is it?

Maybe... Ha, spot on. Ok so this is not easy to do then. Could you explain why structuremap has a hard time knowing how to build these instances?

**Comment by jeremydmiller** [comment]
There's no reason why StructureMap **can't** do this, I was just questioning why you wanted to.

**Comment by NinoFloris** [comment]
I'm not saying it can't, I'm asking why it cannot deduce the correct behavior when doing 

```cs
            Scan(scan =>
            {
                scan.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<,>));
            }
            var handlers = For(typeof(IAsyncRequestHandler<,>));
            handlers.DecorateAllWith(typeof(FirstDecorator<,>));
            handlers.DecorateAllWith(typeof(SecondDecorator<,>));
```

I'd like to understand what it does better.

**Comment by jeremydmiller** [comment]
It's just not built with that use case of open generics in mind is all and it's not magic. If you see the link to the documentation I posted up above, there's an example of what you're trying to do on that page to attach decorators against the open generic type.

Really though, you should probably be talking to @jbogard about MediatR having some kind of formal composition model to make this kind of thing easier to do.

**Comment by jbogard** [comment]
Yeah, this is in the works for MediatR 3.0. I tried to avoid a composition model and push it to the container. But it seems worse and I get all sorts of ?s about how to do it for every container on the planet.

**Comment by jeremydmiller** [comment]
If only you knew of a framework that already does that **exact kind of composition model**...

**Comment by jbogard** [comment]
Yeah I know where I'm stealing my compositional model from. Or at least "inspiration"

**Comment by NinoFloris** [comment]
Alright, for now I have a simple internal implementation also loosely based on owin. Interested to see what @jbogard cooks up for v3.

Wasn't so insanely complicated after all might be the basis for your next tweet @jeremydmiller ;)

**Comment by jeremydmiller** [comment]
My attitude here is that you shouldn't be trying to do things like what you were doing as part of the core of your architecture, period. You're unfortunately running head smack into a sore point with me because of how many people are just killing themselves (and me) with complexity on the StructureMap list as they try to get too fancy with MediatR.

**Comment by NinoFloris** [comment]
Alright and I understand that, and I fully agree.

The only reason I thought I could do this for now easily with structuremap is because one of your acceptance tests has an open generic decorator sample. I'd already read https://github.com/jbogard/MediatR/issues/102 on github for the plans about MediatR 3.0 including a pipeline type of construct by default.

I was hoping to use something like StructureMap's functionality as a tide me over until MediatR 3.0 was ready.

**Comment by jeremydmiller** [comment]
@NinoFloris,

Sorry, but this one is gonna get a "works on my box"
