### ISSUE TITLE
Duplicate source code?

### ISSUE THREAD

**Issue by gravityFlower** [structuremap/structuremap#527]
Hello,

in the documentation on the page [http://structuremap.github.io/the-container/forwarding-requests-for-a-type-to-another-type/](http://structuremap.github.io/the-container/forwarding-requests-for-a-type-to-another-type/) it seems that both code snippets are representing the same code. Instead of displaying the use of Forward<TFrom, TTo>() in the first and the lambda in the second, both seem to display the lambda example.

**Comment by DixonDs** [comment]
You sure? I see the `Forward` usage in the first snippet.

**Comment by gravityFlower** [comment]
Seems like i missed that. Did look the same to me. Sorry.

2017-01-02 10:14 GMT+01:00 Dmytro Dziuma <notifications@github.com>:
