### ISSUE TITLE
.With() not injecting constructor variables 

### ISSUE THREAD

**Issue by mlooise** [structuremap/structuremap#530]
Hi,

I recently tried to switch to StructureMap 4.4.2 but i'm facing a bit of a issue using the With() feature. I'm using StructureMap to set up my ServiceHost for WCF. In order to so i have to create a ServiceHost with some variables given from the actual WCF framework. In order to create the ServiceHost I did the following (inspired by https://lostechies.com/jimmybogard/2008/07/30/integrating-structuremap-with-wcf/):

```
var serviceHost = container
                .With(serviceType)
                .With(baseAddresses)
                .GetInstance<StructureMapServiceHost>();
            return serviceHost;
```

My actual StructureMapServiceHost looks like the following:

```
public class StructureMapServiceHost : ServiceHost
    {
        public StructureMapServiceHost(IContainer container, Type serviceType, params Uri[] baseAddresses)
            : base(serviceType, baseAddresses)
        { .... 
```

With structuremap 4.2.0 everything was working ok with the baseAddresses parameter correctly provider by structuremap when calling the constructor. However, now in V4.4.2, this does not work anymore. The baseAddresses variable stays empty  (empty array). (see below)

I also tried other methods of passing the arguments (explicitArguments) but with the same result. I struggled with it quite some time until I saw the changelog: 

> Performance improvement for some IContainer.With() usages

I'm guessing no coincidence. Does anyone else have the same problem or maybe a resolution? Looks to me as a bug in the new version.

![image](https://cloud.githubusercontent.com/assets/2109791/21389845/0bdef8ac-c784-11e6-837a-2246c68442db.png)

![image](https://cloud.githubusercontent.com/assets/2109791/21389909/56b9875c-c784-11e6-9b64-c4c7c34459d0.png)

![image](https://cloud.githubusercontent.com/assets/2109791/21390002/d047e64a-c784-11e6-917d-21a3a418132e.png)

Kind regards, Martin Looise

**Comment by jeremydmiller** [comment]
I've had a couple complaints about this, usually because of Uri types. As an immediate workaround, you can go to a single type that passes in the service type and the Uri as props or fields on that object. It's counter intuitive, but it'd hit the performance optimization that probably broke this and be significantly faster under any kind of load.

I think I'll finally have to look at this one, but I'm out until after the first of the year.

**Comment by MattHoneycutt** [comment]
I've been doing a little digging on this one.  It looks like With doesn't like array parameters, period.  

The following spec fails:

```
        [Fact]
        public void GetInstance_WithIntArray_PassesIntArrayToConstructedType()
        {
            var container = new Container();

            var instance = container.With(new[] {2}).GetInstance<ServiceThatNeedsInt>();

            instance.Ids.Single().ShouldBe(2);
        }
```

```
    public class ServiceThatNeedsInt
    {
        public int[] Ids { get; }

        public ServiceThatNeedsInt(int[] ids)
        {
            Ids = ids;
        }
    }
```

The service receives an empty array when it is constructed.  I'm still narrowing in on why.  It's been a fun hunt so far! :)

**Comment by jeremydmiller** [comment]
@MattHoneycutt There are a couple places where StructureMap is testing for whether or not a type is an IEnumerable, then dealing with that a little differently. It could easily be that that logic (it's a custom extension method somewhere) is too naive. `String` caused that problem here and there because it's IEnumerable<char>.

**Comment by MattHoneycutt** [comment]
@jeremydmiller Yup, I expected it to be something like that.  I ran out of time to debug further last night, but I plan to pick it back up this evening.

FWIW, I haven't spent a lot of time diving deep into the SM code base before now.  It's been a lot of fun!

**Comment by mlooise** [comment]
@jeremydmiller Thanks! I can also confirm that it now works with the lastest stable 4.4.3. Great job!
