### ISSUE TITLE
Help with performance please

### ISSUE THREAD

**Issue by shaulbehr** [structuremap/structuremap#531]
Hi,
We're using StructureMap 4.4.2.
One of our projects is a consumer for Azure EventHub.  Since we are absorbing a very high rate of incoming messages, our consumers need to work very fast.  And they weren't working fast enough.  So I instrumented some logging in the code, and found a consistent 200ms+ jump over a `container.GetInstance<ISomeInterface>()` line.
200ms doesn't sound like much, but it's a huge deal when we're dealing with hundreds or even thousands of incoming messages per second.
Any clues how I might be able to tighten this up?
Thanks!

**Comment by jeremydmiller** [comment]
Start by looking at the build plan for whatever that type is and go from there: http://structuremap.github.io/diagnostics/build-plans/

**Comment by shaulbehr** [comment]
Thanks for the super-quick response!  I'll investigate and report back soon.

**Comment by jeremydmiller** [comment]
Yeah, but don't expect a fast response coming back. I'm trying to clean my plate of outstanding things today, but I'm gonna be taking a break from any OSS work until after New Year's.

On your side, see if anything jumps out. Anything that's built by a lambda that could be slow, or the object graph is huge, or something else.

**Comment by shaulbehr** [comment]
How do you make it recursive?  The build plan I'm getting goes just one level deep.

**Comment by jeremydmiller** [comment]
Setting 0 as the "max depth" should make it be unlimited. Or jack that number way up.

**Comment by shaulbehr** [comment]
Nm, found it; I set maxLevels to 300.  I thought the 0 default would mean unlimited, but apparently not...

**Comment by shaulbehr** [comment]
Ah, you answered same time as I wrote the above. :)  Nope, the 0 doesn't work as "unlimited".

**Comment by shaulbehr** [comment]
OK, so yes, the plan is pretty deep.  File is 7011 lines long.  But still, if everything is just calling default constructors, that should still be fast enough, no?  Is there any particular string I should search for that's a common flag for something wrong?

**Comment by jeremydmiller** [comment]
I'm not gonna try and guess without any context

**Comment by shaulbehr** [comment]
Thanks, I managed to trim down the dependency tree by separating out some methods into a different class.  That build plan was really helpful.  
Thanks for you help, and happy holidays!
