### ISSUE TITLE
Structuremap is not creating a new object on second web request, however dependency in the object is disposed and no constructor is called.

### ISSUE THREAD

**Issue by robgha01** [structuremap/structuremap#538]
I tried to find this strange behavior bugg and solve it but i just lose my hair on the issue.
I got this code in the client:
https://gist.github.com/robgha01/bc5eec103363f87b7a6828d87beb9731

and this core library that uses Structuremap mvc5 nuget package and the webapi2 package installed. here is the code project for that: https://1drv.ms/u/s!AvOXr9f-QF0p2ECxs1_TgUM-U3RJ

i have both tested with Transient AllwaysUnicue but it just is not working, for some reason when the request ends it can not dispose all properly "the nested request container" im using this to dispose the actual service: (implementing IDisposable) https://lostechies.com/chrispatterson/2012/11/29/idisposable-done-right/

Im also using constructor based approach and some places DependencyResolver.Current.... but for the most part constructor.

is it not supposed to dispose and cleanup at this code snipped (located in the Core library above):
```
public class StructureMapScopeModule : IHttpModule {
    #region Public Methods and Operators

    public void Dispose() {
    }

    public void Init(HttpApplication context) {
        context.BeginRequest += (sender, e) =>
            {
                StructuremapMvc.StructureMapDependencyScope.CreateNestedContainer();
            };
        context.EndRequest += (sender, e) => {
            HttpContextLifecycle.DisposeAndClearAll();
            StructuremapMvc.StructureMapDependencyScope.DisposeNestedContainer();
        };
    }

    #endregion
}
```

**Comment by jeremydmiller** [comment]
What's the actual exception and when does that happen? I don't see anything untoward going on, but I haven't looked at the MVC & Web API adapters in a long time.

**Comment by robgha01** [comment]
Well when i request a second time it jumps into my UserService.IsAuthenticated() however the webSecurity object is null as the constructor is not called i think structuremap is using the disposed object a second time or someting.

**Comment by jeremydmiller** [comment]
What version of StructureMap are you using? You should get an ObjectDisposedException in that case on any recent version of StructureMap.

**Comment by robgha01** [comment]
Im using 4.4.2

**Comment by jeremydmiller** [comment]
Yeah, so it's not the nested container being disposed, and if it were sharing the nested container erroneously, you would just be getting the same set of objects. I think I'd tell you to look into how it's doing the nested container scoping to the HttpContext.

**Comment by robgha01** [comment]
I just spotted one strange thing
`public class StructureMapDependencyScope : ServiceLocatorImplBase`
is not implementing a IDisposable but it has a public void Dispose() { function

may that be the reason StructureMapScopeModule end request is not calling the dispose... its a stupid mistake but il test if it is resolved...

**Comment by robgha01** [comment]
Finally i think its all solved it was multiple problems first i had a cache layer that was acting a bit bad,
then i had some minor problems with the actual core project replaced HttpContext which used container.TryGet... moved that logic to constructor parameter Func<HttpContextBase> for unit testing instead.

Thanks for giving me inputs on the problem it helped me rethink 👍 
Hope is key, Key is sleep... Sleep is wonderfull 🛌
