### ISSUE TITLE
Unable to create a build plan for concrete type

### ISSUE THREAD

**Issue by fabriciogd** [structuremap/structuremap#548]
The problem occurs on the application startup, more frequently in IIS express.
Structuremap: 4.4.1

`Unable to create a build plan for concrete type Func<IFabricaDeFiltros> new Func<IFabricaDeFiltros>(Object, IntPtr method) ┗ Object = **Default** IntPtr method = Required primitive dependency is not explicitly defined 1.) Attempting to create a BuildPlan for Instance of Func<IFabricaDeFiltros> -- Func<IFabricaDeFiltros> 2.) new Lazy'1(*Default of Func<IFabricaDeFiltros>*, Value: True) 3.) Lazy<IFabricaDeFiltros> ('24b48df4-b4eb-42d1-84e2-0f5877c84572') 4.) Instance of Lazy<IFabricaDeFiltros> ('24b48df4-b4eb-42d1-84e2-0f5877c84572') 5.) new ConsultaDePessoa(*Default of Lazy<IConsulta<PessoaFisica>>*, *Default of Lazy<IConsulta<PessoaFisicaFiliacao>>*, *Default of Lazy<IConsulta<PessoaJuridica>>*, *Default of Lazy<IConsultaDeAluno>*, *Default of Lazy<IConsultaDeEnumeradorSis>*, *Default of Lazy<IConsultaDePapel>*, *Default of Lazy<IConsultaDeTipoDocumento>*, *Default of Lazy<IConsultaDeUsuario>*, *Default of Lazy<IConsultaDeVinculoSetorAtendimento>*, *Default of Lazy<IConsultaDeVwDePessoaFisicaNome>*, *Default of Lazy<IConsultaDeContrato>*, *Default of Lazy<IFabricaDeFiltros>*) 6.) Centris.Dados.Core.Consultas.ConsultaDePessoa 7.) Instance of Centris.Consultas.Core.IConsultaDePessoa (Centris.Dados.Core.Consultas.ConsultaDePessoa) 8.) Container.GetInstance<Centris.Consultas.Core.IConsultaDePessoa>() Details…	`

**Comment by jeremydmiller** [comment]
@fabriciogd This isn't a bug. Just like the exception is telling you, it needs you to specify a value for the `IntPtr` constructor parameter of whatever the concrete type is. StructureMap doesn't guess with primitive values like that.

**Comment by fabriciogd** [comment]
The concret type of IFabricaDeFiltros doesn't have constructor.

**Comment by jeremydmiller** [comment]
`Func<IFabricaDeFiltros>(Object, IntPtr method)` does though.

**Comment by jeremydmiller** [comment]
Why are you registering all the Lazy's and Func's?

**Comment by fabriciogd** [comment]
Classes have many dependencies, so we declare all as lazy, to be initialized on demand.

```cs
public ConsultaDePessoa(
	Lazy<IConsulta<PessoaFisica>> consultaDePessoaFisica,
	Lazy<IConsulta<PessoaFisicaFiliacao>> consultaDePessoaFisicaFiliacao,
	Lazy<IConsulta<PessoaJuridica>> consultaDePessoaJuridica,
	Lazy<IConsultaDeAluno> consultaDeAluno,
	Lazy<IConsultaDeEnumeradorSis> consultaDeEnumeradorSis,
	Lazy<IConsultaDePapel> consultaDePapel,
	Lazy<IConsultaDeTipoDocumento> consultaDeTipoDocumento,
	Lazy<IConsultaDeUsuario> consultaDeUsuario,
	Lazy<IConsultaDeVinculoSetorAtendimento> consultaDeVinculoSetorAtendimento,
	Lazy<IConsultaDeVwDePessoaFisicaNome> consultaDeVwDePessoaFisicaNome,
	Lazy<IConsultaDeContrato> consultaDeContrato,
	Lazy<IFabricaDeFiltros> fabricaDeFiltros
)
{
	_consultaDePessoaFisica = consultaDePessoaFisica;
	_consultaDePessoaFisicaFiliacao = consultaDePessoaFisicaFiliacao;
	_consultaDePessoaJuridica = consultaDePessoaJuridica;
	_consultaDeAluno = consultaDeAluno;
	_consultaDeEnumeradorSis = consultaDeEnumeradorSis;
	_consultaDePapel = consultaDePapel;
	_consultaDeTipoDocumento = consultaDeTipoDocumento;
	_consultaDeUsuario = consultaDeUsuario;
	_consultaDeVinculoSetorAtendimento = consultaDeVinculoSetorAtendimento;
	_consultaDeVwDePessoaFisicaNome = consultaDeVwDePessoaFisicaNome;
	_consultaDeContrato = consultaDeContrato;
	_fabricaDeFiltros = fabricaDeFiltros;
}
```

**Comment by jeremydmiller** [comment]
@fabriciogd I'm closing this. It's not a StructureMap bug and I'm trying to clean out our issue list. Double check how you're registering `Func<IFabricaDeFiltros>`
