### ISSUE TITLE
Inconstant behaviour between Child Containers and Profiles for Singletons

### ISSUE THREAD

**Issue by Pvlerick** [structuremap/structuremap#552]
Given these types:

```csharp
interface I { string M(); }

class C : I
{
	private readonly IFoo foo;

	public C(IFoo foo) { this.foo = foo; }

	public string M() => this.foo.M();
}

interface IFoo { string M(); }

class Foo : IFoo { public string M() => nameof(Foo); }

class AlternateFoo : IFoo { public string M() => nameof(AlternateFoo); }
```

If I declare a container as such

```csharp
var container = new Container(c =>
{
	c.For<I>().Use<C>().Singleton();
	c.For<IFoo>().Use<Foo>().Singleton();

	c.Profile("a", p =>
	{
		p.For<I>().Use<C>().Singleton();
		p.For<IFoo>().Use<AlternateFoo>().Singleton();
	});
});
```

When requesting a type ```C``` on the root or on the "a" profile, I get different instances of ```C``` which have different injected ```IFoo``` (correct behaviour I believe since each should have its singleton):

```csharp
//Requesting "C" (implementation)
container.GetInstance<C>().M().ShouldBe(nameof(Foo)); //OK
container.GetProfile("a").GetInstance<C>().M().ShouldBe(nameof(AlternateFoo)); //OK
```

However, when requesting an ```I```, I get two different instances on the root and on the profile but they have been injected the same ```IFoo``` in both cases (```Foo```):

```csharp
//Requesting "I" (abstraction)
container.GetInstance<I>().M().ShouldBe(nameof(Foo)); //OK
container.GetProfile("a").GetInstance<I>().M().ShouldBe(nameof(AlternateFoo)); //Fails

//Just checking...
Assert.NotSame(container.GetInstance<C>(), container.GetProfile("a").GetInstance<C>()); //OK
Assert.NotSame(container.GetInstance<I>(), container.GetProfile("a").GetInstance<I>()); //OK
```

On the other hand, if I create a child container as such:

```csharp
var childContainer = container.CreateChildContainer();
childContainer.Configure(c =>
{
	c.For<I>().Use<C>().Singleton();
	c.For<IFoo>().Use<AlternateFoo>().Singleton();
});
```

Then I get the _correct_ behaviour:

```csharp
childContainer.GetInstance<I>().M().ShouldBe(nameof(AlternateFoo)); //OK
childContainer.GetInstance<C>().M().ShouldBe(nameof(AlternateFoo)); //OK
```

I didn't dig into this too much, but it seems that, [contrarily to what the documentation states about profiles](https://structuremap.github.io/the-container/profiles-and-child-containers/)

> Profiles are just named child containers that may be configured upfront through Registry configurations.

Profiles and child containers are not the same.

I'm not sure if this is by design or an actual bug :-)

Full Gist [here](https://gist.github.com/Pvlerick/9782102959d480518b611086d4ee1873#file-issue-cs).

**Comment by jeremydmiller** [comment]
@Pvlerick Profiles are just named child containers behind the scenes. If there's a bug, it's a bug in child containers. I'll look at this later in the week.

Honestly, you're getting into use cases I never considered with child containers and the rules about scoping. I threw child containers into the 3.0 release, but I don't use them myself and that frequently shows.
