### ISSUE TITLE
.IsIO

### ISSUE THREAD

**Issue by silkfire** [structuremap/structuremap#555]
At the moment, this code:

```
 _.For<IDbConnection>()
  .Use<MySqlConnection>()
  .Ctor<string>("connectionString")
  .Is(() => Configuration.GetConnectionString("DefaultConnection"));
```
   

fails as _Configuration.GetConnectionString("DefaultConnection")_ returns null.

But rewriting above code explicitly like this:

```
 _.For<IDbConnection>()
  .Use(() => new MySqlConnection(Configuration.GetConnectionString("DefaultConnection")));
```

Makes it work. What gives?

**Comment by jeremydmiller** [comment]
Are you sure you've got the ctor argument right, and is it really defaulting to the SqlConnection constructor that you think it is? StructureMap doesn't do any magic, read the tea leaves logic to pick a constructor by default.

There's nothing here to do, so I'm closing this one.
