### ISSUE TITLE
Dynamic Interception assembly issue with ASP.NET Core 1.1

### ISSUE THREAD

**Issue by robymes** [structuremap/structuremap#560]
I can't make Dynamic Interception work with ASP.NET Core 1.1

- fresh asp.net core project in Visual Studio 2017
- added StructureMap.AspNetCore from nuget
- configured StructureMap.AspNetCore: build & run ok
- added a custom service (IFoo, Foo) to registry: build & run ok
- added StructureMap.DynamicInterception
- added custom ISyncInterceptionBehavior
- configured registry to intercept custom service with custom interceptor
- build -> ok
- run -> error: `FileLoadException: Could not load file or assembly 'StructureMap, Version=4.4.3.571, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

is Dynamic Interception intended to work in .NET Core?

**Comment by jeremydmiller** [comment]
Probably a duplication of #559

**Comment by robymes** [comment]
I don't know if it's an exact duplication of #559: the exception is the same, but in my case the standard asp.net core integration works well simply using StructureMap.AspNetCore, then I received the exception introducing StructureMap.DynamicInterception.
I think StructureMap.AspNetCore doesn't have a dependency on StructureMap, instead StructureMap.DynamicInterception has it.
at the end maybe the problem is the same, but I don't have much knowledge of StructureMap internals

**Comment by jeremydmiller** [comment]
@robymes I don't think this has anything whatsoever to do with SM internals. I think this is all Nuget woes. VS2017 clearly changes Nuget behavior and it's causing me aggravation on several other projects too. If you'd be up for that, we have gotten reports that some of the Nuget resolution problems go away if you use Paket

**Comment by DixonDs** [comment]
@jeremydmiller so far, what I see, the latest published StructureMap 4.4.3 assembly has version 4.4.3.564, but StructureMap.DynamicInterception is build with dependency on StructureMap 4.4.3.571.

**Comment by jeremydmiller** [comment]
@DixonDs The Nuget versioning is set to >4.4.3 and the assemblies are unsigned. That really shouldn't matter since everything is unsigned.

@robymes What .Net version are you targeting, and how are you resolving nugets? With the new VS2017 version of csproj and version of the dotnet cli? Can you actually check whether or not the StructureMap nuget is correctly installed and the StructureMap.dll is in your bin directory?

**Comment by jeremydmiller** [comment]
@DixonDs @robymes New nugets are up for StructureMap 4.4.4, AutoFactory 1.0.1, and DynamicInterception 1.0.2. Try those and see if the binding problems go away?

**Comment by robymes** [comment]
thanks a lot, I'll try and I'll give you feedback

**Comment by robymes** [comment]
Great! it works
Thank you
