### ISSUE TITLE
.With(...) not injecting constructor variable

### ISSUE THREAD

**Issue by knoxi** [structuremap/structuremap#562]
Hi, 

We updated from V4.4.2 to V4.4.4 and now the constructor injecting .With(...) is no longer working.

Code:
`IList<ISlice> slice;`
`...`
`this.container.With(slice).GetInstance<ISliceViewModel>()`

ctor of `ISliceViewModel`: 
`        public SliceViewModel(IList<ISlice> slice)
        { ...
`

The content of the slice variable is not passed in, but a new instance is created instead.

**Comment by jeremydmiller** [comment]
Taking a look at this now...

**Comment by jeremydmiller** [comment]
The fix for this one will be in StructureMap 4.4.5 later today
