### ISSUE TITLE
[Question] custom lifecycle based on an Event Is it possible ?

### ISSUE THREAD

**Issue by HamedFathi** [structuremap/structuremap#567]
I have LoadEngine for loading assemblies and types.

When an assembly changed (eg replaced by new one), It calls OnChange() event

I want to know how to write custom lifecycle based on OnChange() means when somethings changed I recreate object or replace object in container with new instance ?

for example in another IOC (LightInject) I can do like this 

```
public class LoadEngineLifeCycle<T> : ILifetime where T : class
    {
        private bool _isChanged = false;
        private LoadEngine<T> _loadEngine;
        private object _lastInstance = null;
        public LoadEngineLifeCycle(LoadEngine<T> loadEngine)
        {
            loadEngine.OnChange += () => _isChanged = true;
            _loadEngine = loadEngine;
        }
        public object GetInstance(Func<object> instanceFactory, Scope currentScope)
        {
            if (_isChanged)
            {
                _isChanged = false;
                _lastInstance =  _loadEngine.GetInstance();
                return _lastInstance;
            }
            if (_lastInstance == null)
            {
                return instanceFactory();
            }
            else
            {
                return _lastInstance;
            }
        }
    }
```

Is this possible in structuremap too ?
Can anyone guide me ?

**Comment by jeremydmiller** [comment]
Would you want to deal with that with a lifecycle, or by just ejecting existing values? You can always use the `IContainer.Model` object to do that: http://structuremap.github.io/diagnostics/using-the-container-model/

**Comment by jeremydmiller** [comment]
This for building your own lifecycle: http://structuremap.github.io/object-lifecycle/custom-lifecycles/

**Comment by HamedFathi** [comment]
@jeremydmiller , 

Actually you right I needed to eject existing value so I tested your guide and it works perfectly

Thanks
