### ISSUE TITLE
Get Requesting Type and Requested Type

### ISSUE THREAD

**Issue by no1melman** [structuremap/structuremap#570]
I have two scenarios.

First, I have `IOptionsManager` which has a method `IOptions<T> GetOptions<T>()`. In a constructor I wish to do `IOptions<MyCustomOptions> customOptions`. Is it possible to in the container configuration to do something like:

```
cfg.For(typeof(IOptions<>))
    .Use("OptionsManager Creator", ctx =>
    {
        var optionType = ctx.RequestedType.GenericTypeArguments.First();
                        
        var optionsManager = ctx.GetInstance<IOptionsManager>();

        var invoke = optionsManager.GetType().GetMethod("GetOptions").MakeGenericMethod(optionType).Invoke(optionsManager, null);

        return invoke;
    }).Singleton();
```

Where `RequestedType` would be `IOptions<MyCustomOptions>`

Second, I have an `ApplicationLoggerFactory` that has `Create(string domain)` where the `string domain` is just the type that asked for the logger. So if `MyClass` request `ILogger` the DI would pass `"MyClass"` to the create parameter of the `ApplicationLoggerFactory`.

Something like:

```
cfg.For<IApplicationLogger>()
    .Use("Application Logger Factory", ctx =>
    {
        var requesterTypeName = ctx.RequesterType.Name;
        return ctx.GetInstance<IApplicationLoggerFactory>().Create(requesterTypeName, LoggerType.Log4Net);
    });
```

**Comment by no1melman** [comment]
The answer to the second question is

``` ctx.ParentType.Name; ```

**Comment by no1melman** [comment]
For the first question, I've done this:

```

var optionTypes = typeof(IOptions<>).Assembly.GetTypes()
    .Where(x => typeof(IOptionsSection).IsAssignableFrom(x) && x.IsClass && !x.IsInterface && x.IsPublic)
    .ToList();
foreach (var t in optionTypes)
{
    var optionType = typeof(IOptions<>).MakeGenericType(t);
    cfg.For(optionType)
        .Use("OptionsManager Creator", ctx =>
        {
            var optionsManager = ctx.GetInstance<IOptionsManager>();

            var task = (Task)optionsManager.GetType()
                .GetMethod("GetOptions")
                .MakeGenericMethod(t)
                .Invoke(optionsManager, null);

            var result = task.GetType().GetProperty("Result").GetValue(task);

            return result;
        })
        .Singleton();
}

```

But it doesn't feel right...

**Comment by jeremydmiller** [comment]
@no1melman "But it doesn't feel right..." -- there's a much easier way to handle this kind of scenario. See this topic http://structuremap.github.io/registration/on-missing-family-policies/, but scroll down until you see the example on `SettingInstance<T>` that was taken from our FubuMVC version of IOptions.

**Comment by no1melman** [comment]
Perfect - thought this shouldn't be too difficult!
