### ISSUE TITLE
The Gentile Quickstart may benefit from one more step or wording update..

### ISSUE THREAD

**Issue by StingyJack** [structuremap/structuremap#571]
The steps seem to include..

Given this object model
 - this is how to register an implementation to an instance
 - this is how to resolve an a specific implementation when you have the container present in scope

...but not how to **get** instances from the container in other points in the application. This may be considered OT, but as a noob I would probably scratch my head and go look somewhere else because this doesnt tell me how (or why) to _use_ it in an actual application.

**Comment by DixonDs** [comment]
@StingyJack  Do you mean to extend "Integrating StructureMap within your application" section with some code examples? The problem is that it is very specific to the application type you work with, so it might be hard to get some generic and still useful for most people example there.

**Comment by jeremydmiller** [comment]
@StingyJack I've got to say ditto to what @DixonDs said. That's very specific to whatever application framework you're using. I wouldn't consider it "quickstart" material, but a link to the section on [auto wiring](http://structuremap.github.io/the-container/auto-wiring/) might be helpful.

If you're just wanting to use service location within your application - which we don't recommend in most use cases - you can just accept `IContainer` as a constructor argument in your class.

If you have any specific recommendations here, feel very free to send a pull request in on the quickstart docs. It's just a markdown file in GH.

**Comment by StingyJack** [comment]
A bit more "distance" in the existing example between registration and point of use than a single method (or class) scope would be closer to what I'm thinking.

**Comment by StingyJack** [comment]
> That's very specific to whatever application framework you're using.

You mean the .net framework? 

> If you're just wanting to use service location 

I'm a noob (to DI/IoC "frameworks") and don't know what I want, or why service location is "evil" (especially compared with some of the abominations I see periodically).  

So you can "auto wire", and that page talks about using the specific dependencies in the ctor instead of passing the container around and talks about a build plan, but it doesnt actually show how one gets an instance of ShippingScreenPresenter to use later in the application. The docs all point to IContainer, which is locally scoped and I think adding it in a constructor is what you mean by "not recommended".

**Comment by jeremydmiller** [comment]
@StingyJack Nah, I'm saying it's very different from ASP.Net MVC to Web API to any of the service bus frameworks.

**Comment by jeremydmiller** [comment]
I'm just not seeing anything concrete here.

**Comment by StingyJack** [comment]
> I'm just not seeing anything concrete here.

Me neither, but I do appreciate the pun/irony.
