### ISSUE TITLE
Best way for real app to do per request life time in net core app

### ISSUE THREAD

**Issue by juandrn** [structuremap/structuremap#576]
I dont know how to do it I know I need to do a nested container, but in real app you define all in constructor

My question is How do you pass the nested instance for already existing constructor, I'm thinking to get the instance and pass it throught method but I think It is a ugly way

Code only for example:

```csharp

public class IData{//This class has per request life time.
       ...
       void SaveSomething()
       ...
}

public class IBusiness{//This class is singleton
       ...
       void DoSomeThing();
       ...
}

public class BusinessImplementation : IBusiness{
          public IData data;
          void BusinessImplementation (IData data){
                    this.data = data; //How to make this with per request life time
          }

          public void DoSomeThing(){
                  this.data.SaveSomething();
          }
}

public class WebApiController{
           public IBusiness business;
           WebApiController(IBusiness business, IContainer container){
                    this.business = business;
                    this.container = container;
           }
           
           public void AnyMethod(){
                  using (var child = container.GetNested())
                  {
                           //Here the question How to make a IData instance with per request life time?.
                           business.DoSomeThing(); 
                           
                           //Should I pass the instance throught method?
                           business.DoSomeThing(child.GetInstance<IData>()); //Exists a best way?
                           
                  }
           }
}
```

**Comment by jeremydmiller** [comment]
If you take a constructor argument of `IContainer`, you'll get the container that created the object. If it was created by a nested container within an ASP.Net Core request, you'd get that container.

In your code above, it'd be easier to just inject in the `IData`, or do it lazily with `Lazy<IData>`. In general, try not to inject the container itself into your controllers.

**Comment by juandrn** [comment]
Sorry, I don't understand very well, could you show me a sample code please? I'll appreciate it

**Comment by jeremydmiller** [comment]
Try this, with comments:

```
public class BusinessImplementation : IBusiness{
          public IData data;
          void BusinessImplementation (IData data){
                    this.data = data; //How to make this with per request life time
          }

          public void DoSomeThing(){
                  this.data.SaveSomething();
          }
}

public class WebApiController{
           public IBusiness business;
           WebApiController(IBusiness business, IData data){
                    this.business = business;
                    this.data = data;
           }
           
           public void AnyMethod(){
                       //Here the question How to make a IData instance with per request life time?.
                       business.DoSomeThing(); 
                           
                       //Should I pass the instance throught method?
                      business.DoSomeThing(this.data); //Exists a best way?

           }
}
```

If `IData`, `BusinessImplementation`, and `WebApiController` are all built by the per request nested container, there would only be on `IData` object created and you can just inject that dependency.

**Comment by juandrn** [comment]
Ok I understand your view point now, but when I'll do the dispose of IData instance when finish web api method, because in the above example never is called the Dispose method.

Because I need that the instance keep a live only for the Web Api call, but I'm thinking that I need to pass the instance for the method.

I don't know if I explain well,

**Comment by juandrn** [comment]
Or in other question How I do the Scoped life time of default dependency injection of Net Core in StructureMap.
Ref
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection

Because in the structure map article It let me confused because I need to make a nested container to make a per request life time.
- First define a Transient life time of structure map and then making a Nested container inner using block to dispose.
Ref
http://structuremap.github.io/object-lifecycle/supported-lifecycles/

**Comment by jeremydmiller** [comment]
@juandrn, If you're using Web API, it's building a nested container per request. StructureMap's **default** lifecycle is essentially the same behavior you'd get from the container-scoped lifecycle concept in ASP.Net Core. There's literally nothing else you need to do. As for `Dispose()`, the nested container tracks every object it creates that implements `IDisposable` and disposes it when the nested container itself is disposed.

**Comment by juandrn** [comment]
Ok, you're right, I've edited the Microsoft sample code and checked what you said, thank you.

All edited code is just in the startup class in ConfigureService Method:
[Sample Code] https://yadi.sk/d/buLhVWcD3JgF5b
