### ISSUE TITLE
Nullable types as constructor arguments cause issues

### ISSUE THREAD

**Issue by eeisenbr** [structuremap/structuremap#578]
If you have a concrete class that takes nullable types as constructor arguments, and pass them all in using ExplicitArguments, it doesn't work because the types of the arguments are not nullable, and StructureMap doesn't consider nullable types to be "simple", so it tries to inject the arguments and fails.  Here's the fix I came up with:
https://github.com/eeisenbr/structuremap/commit/23f709bfe19a9aa3e2ba20f894dcbe37ca2aa3c1
I'm working on adding unit tests.

**Comment by jeremydmiller** [comment]
@eeisenbr Hey Ned, next time -- if there is one -- let me know you're from TAS/WTW and I'll respond a whole lot faster;) The fix is fine if all the tests pass, but I'd ask that you extract the logic to its own method.

**Comment by eeisenbr** [comment]
No worries, there's no immediate urgency on this one.  Thanks though.

Two questions:

1. Would you prefer I put the new method in DependencyCollection or in TypeExtensions?  I'm leaning toward just keeping it in DependencyCollection but I can see arguments either way.
2. When I run all of the tests in VS 2017, it just locks up after running 68 of them.  What method do you use?

**Comment by jeremydmiller** [comment]
@eeisenbr In DependencyCollection is fine. I use either the rake script that just delegates to dotnet test or the Resharper runner. Used to use TestDriven.Net, but that doesn't work w/ VS2017 very well yet.

**Comment by eeisenbr** [comment]
@jeremydmiller Thanks for the info.  I thought rake was just for compiling the documentation.  I've done the refactoring https://github.com/eeisenbr/structuremap/commit/046e635524b39de1636bd18f5f36921947fe64fc
Let me know if this looks okay to you.

**Comment by jeremydmiller** [comment]
@eeisenbr Looks good to me. Ship it!
