### ISSUE TITLE
Missing HttpContext lifecycle samples in documentation

### ISSUE THREAD

**Issue by hognevevle** [structuremap/structuremap#587]
Hi,

On http://structuremap.github.io/object-lifecycle/supported-lifecycles/#sec5 , there are two samples missing at the bottom. 

Is there anywhere those can be seen?

**Comment by jeremydmiller** [comment]
They *should* still be in the 3.1 branch, but I couldn't find the samples. For clean up, it's this: https://github.com/structuremap/structuremap/blob/3.1/src/StructureMap.Web/Pipeline/HttpContextLifecycle.cs#L47-L50. With the StructureMap.Web assembly, you should see some extension methods to apply the old ASP.Net lifecycles.

First though, why do you still need this? Should be unnecessary in most of the current web frameworks I'm familiar with (asp.net mvc, mvc core, nancy, web api)
