### ISSUE TITLE
Problems resolving dependencies (for MediatR handlers) in Azure Web App environments

### ISSUE THREAD

**Issue by tjrobinson** [structuremap/structuremap#588]
_This is cross-posted as https://github.com/jbogard/MediatR/issues/184 because I'm not sure whether it's a MediatR or a structuremap issue (or more likely just me doing something wrong)._

I've got a strange issue which I can only reproduce when I deploy my site as an Azure Web App.

- MediatR 3.0.0
- ASP.NET Core 1.1.2 w/ .NET 4.6.2
- Azure Web App
- AutoMapper.Extensions.Microsoft.DependencyInjection 2.0.1
- MediatR.Extensions.Microsoft.DependencyInjection 2.0.0
- StructureMap.Microsoft.DependencyInjection 1.3.0
- StructureMap 4.5

I get this error in Azure:

`
InvalidOperationException
Handler was not found for request of type Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Command. Container or service locator not configured properly or handlers not registered with your container.`

Running locally from Visual Studio 2017 it works fine.

I've added some logging so I can check what's registered in the container (StructureMap).

```
foreach (var instanceRef in container.Model.AllInstances)
{
    Log.Information("Registered with container: {PluginType} {ReturnedType}", instanceRef.PluginType.FullName, instanceRef.ReturnedType.FullName);
}
```

This shows the following entries relevant to the above error (interestingly I get each one twice, whether locally or in Azure):

* Registered with container: MediatR.IAsyncRequestHandler`2[[Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Command, Empactis.Scheduler.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MediatR.Unit, MediatR, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]] Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Handler
* Registered with container: MediatR.IAsyncRequestHandler`2[[Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Command, Empactis.Scheduler.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[MediatR.Unit, MediatR, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]] Empactis.Scheduler.Web.Model.Handlers.Events.UpdateEvent+Handler

I've spent a few hours on this trying various things, cleaning environments, checking for config differences etc but nothing adds up.

Any help would be much appreciated.

I realise this probably doesn't contain all the information you need (as I don't know what the likely cause is) so let me know what other information would be helpful.

**Comment by tjrobinson** [comment]
I think I've sorted this now. A dependency deep down in the dependency tree can't be resolved, causing the handler to not be able to be resolved. What was throwing me was the wording of the error from MediatR making me focus on something specific to the handler rather than its dependencies.

**Comment by tjrobinson** [comment]
Just over a year later and I've come across the same error in the same bit of code!

For my future self and others - the proper fix is to not initialise things in the constructor, or if you do, at least put a try/catch round it and log it. If there's an exception in the constructor of a dependency, you don't get much detail in the exception from MediatR so it's very hard to work out the problem.

**Comment by lnaie** [comment]
> Just over a year later and I've come across the same error in the same bit of code!
> 
> For my future self and others - the proper fix is to not initialise things in the constructor, or if you do, at least put a try/catch round it and log it. If there's an exception in the constructor of a dependency, you don't get much detail in the exception from MediatR so it's very hard to work out the problem.

yes indeed. another possible case of dramatic failure would be when using constructor injection and you'll be injecting IOptions<T> dependency that loads stuff from the appsettings.json and these settings are not configured in azure in the release variables. :))

have fun!
