### ISSUE TITLE
StructureMap 4.5.x NuGet package installation fails

### ISSUE THREAD

**Issue by wdupree** [structuremap/structuremap#590]
Upgrading from 4.4.5 to 4.5.0 or 4.5.1 results in an error and rolls back the changes giving the following message in the Output window:

  GET https://api.nuget.org/v3/registration2-gz/structuremap/index.json
  OK https://api.nuget.org/v3/registration2-gz/structuremap/index.json 275ms
Restoring packages for 'BCBSLA-Proto'.
Restoring packages for C:\Local Work Files\PersonalTFS\BCBSLA-Proto\project.json...
System.Reflection.Emit.Lightweight 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.Lightweight 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.Lightweight 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
System.Reflection.Emit.ILGeneration 4.3.0 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'BCBSLA-Proto'.
Package restore failed. Rolling back package changes for 'BCBSLA-Proto'.
========== Finished ==========
Time Elapsed: 00:00:02.4702849

This is a UWP in Visual Studio 2015. I haven't had any issues updating until now - any one have any suggestions? Thanks!

**Comment by jeremydmiller** [comment]
@wdupree Man, I'm sorry, but I think the answer right now is to stay back on 4.4.5. That dependency was introduced for the 1st time in 4.5 (it's a big perf optimization win). There's very little change from 4.4.5 to 4.5 otherwise. Just some oddball use cases

**Comment by wdupree** [comment]
ok - thanks @jeremydmiller. Do you know if it's a limitation of being on Visual Studio 2015? I know that there's a limitation of updating the .NETCore UWP nuget package to 5.3.x because it's dependent on Visual Studio 2017 (which required Windows 10 to develop UWP apps where '15 doesn't).

**Comment by dadhi** [comment]
@jeremydmiller, is it a FEC dependency?

**Comment by jeremydmiller** [comment]
@dadhi Yes. I did cheat a little bit and just grabbed the one class and made it internal to SM.

**Comment by dadhi** [comment]
I am excluding Fec from DryIoc for UWP and some old PCLs.

**Comment by jeremydmiller** [comment]
Ah, gotcha. That's what I get for trying to do that. @wdupree I'll make a 4.5.2 soon that just takes FEC as a dependency so I can rely on his Nuget dependency work;)

**Comment by dadhi** [comment]
Btw, I am cheating too, including the Fec file for supported platforms and excluding for not supported. 

To handle its abcense I am inserting a partial method at the top of `ExpressionCompiler` class:

    public static partial class ExpressionCompiler
    {
        // ReSharper disable once RedundantAssignment
        static partial void TryCompile<TDelegate>(ref TDelegate compileDelegate,
            Expression bodyExpr,
            IList<ParameterExpression> paramExprs,
            Type[] paramTypes,
            Type returnType) where TDelegate : class
        {
            compileDelegate = TryCompile<TDelegate>(bodyExpr, paramExprs, paramTypes, returnType);
        }

    // the rest

Then on container side I have the other part:

    namespace FastExpressionCompiler
    {
    using System;
    using System.Linq.Expressions;
    using System.Collections.Generic;

    /// <summary>Compiles to delegate using FastExpressionCompiler.</summary>
    public static partial class ExpressionCompiler
    {
        internal static TDelegate DoCompile<TDelegate>(Expression bodyExpr,
            ParameterExpression[] paramExprs, Type[] paramTypes, Type returnType) where TDelegate : class
        {
            TDelegate compiledDelegate = null;
            TryCompile(ref compiledDelegate, bodyExpr, paramExprs, paramTypes, returnType);
            return compiledDelegate;
        }

        static partial void TryCompile<TDelegate>(
            ref TDelegate compileDelegate,
            Expression bodyExpr,
            IList<ParameterExpression> paramExprs,
            Type[] paramTypes,
            Type returnType) where TDelegate : class;
    }
    }

Container calls `DoCompile`, and if result is null, fallbacks to `Expression.Compile`

**Comment by wdupree** [comment]
Cool - thanks for the info!
