### ISSUE TITLE
StructureMap.Pipeline.LifecycleObjectCache not marked as serializable

### ISSUE THREAD

**Issue by apeneve** [structuremap/structuremap#600]
When I switched from in memory to SQL Server for storing session data in asp.net, I get a SerializationException: `Type 'StructureMap.Pipeline.LifecycleObjectCache' in Assembly 'StructureMap, Version=3.1.9.463, Culture=neutral, PublicKeyToken=e60ad81abae3c223' is not marked as serializable.` Is it possible to get around this in some way? Can the LifecycleObjectCache be decorated with a Serializable attribute, perhaps?

No code in my solution tries to store instances of LifecycleObjectCache in session, so I'm unsure where this error originates from.

**Comment by jeremydmiller** [comment]
@apeneve I think you need to look through your code and see what's either referencing the StructureMap container or maybe even a Func<T> or Lazy<T> that's filled by the container, and eliminate that reference.

**Comment by apeneve** [comment]
Sees to be a problem in the CMS (EPiServer) I'm using.

**Comment by rickythefox** [comment]
@apeneve care to elaborate? Getting the same error here and I'm also using EPiServer.

**Comment by apeneve** [comment]
My troubles disappeared after an EPiServer upgrade, so I did not pursue it any further. I'm now running cms 11.something and structuremap 4.5.3 without any issues.
