### ISSUE TITLE
Structuremap Build Exception Seemingly Related to Scale

### ISSUE THREAD

**Issue by JKSnd** [structuremap/structuremap#601]
Edit: This issue is in regard to v4.4.3

I'm working on a desktop system that communicates with up to ~250 networked devices concurrently. We use structuremap under MediatR to decouple our view models from the networking logic.

When a small number of devices are connected (1-30 or so) everything works smoothly. Interestingly, when more devices are connected (say, 60) structuremap starts throwing bi-directional dependency exceptions when asked to resolve objects that it had previously done successfully.

Given that the same objects are successfully resolved when the number of devices is low, it seems reasonable that the "bidirectional" exception is a false positive. How can I go about determining the actual cause of the exception, since there definitely not any bidirectional dependencies in the code.

Thanks for your help!

Some extra notes:

- The particular type resolution that causes this exception appears to be random between sessions.

- At the time that these exceptions are thrown, one could expect that each device will have a queue of requests messages about 10 deep to get through.

**Comment by JKSnd** [comment]
@jeremydmiller, I created a Gist that has some XUnit tests in it that display this beahviour

https://gist.github.com/JKSnd/1bef8e59dd68398fda7cd984d203b368

Requires: 

- MediatR 2.0.2

- StructureMap 4.4.2

- XUnit 2.2.0

**Comment by jeremydmiller** [comment]
@jbogard Is there anything going on inside of MediatR that would be registering services to the container on the fly? I feel like I've seen something similar before from the MediatR + SM combo.

@JKSnd Are you 100% you don't actually have a bi-directional relationship? The stack trace that SM spits out should tell you the order of construction & dependency.

**Comment by JKSnd** [comment]
@jeremydmiller  I am 100% certain, yes. The example in that gist uses classes that are highly independent and the issue still manifests. It does seem to be a bit of a heisenbug, as subsequent runs do produce different results.

Here's an example stack trace from our software's most recent release candidate:

> Anonymously Hosted DynamicMethods Assembly : StructureMap.Building.StructureMapBuildException
Bi-directional dependency relationship detected!
Check the StructureMap stacktrace below:
1.) Instance of INotificationHandler<RefreshingFromRemoteFinished> (Pk.Network.Communication.CommonProductCommandHandlers.PausePollingCommandHandler)

>   at lambda_method(Closure , IBuildSession , IContext )
   at StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
   at StructureMap.BuildSession.BuildNewInSession(Type pluginType, Instance instance)
   at StructureMap.BuildSession.BuildUnique(Type pluginType, Instance instance)
   at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   at StructureMap.BuildSession.FindObject(Type pluginType, Instance instance)
   at StructureMap.BuildSession.<>c__DisplayClass26_0.<GetAllInstances>b__0(Instance x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at StructureMap.BuildSession.GetAllInstances(Type pluginType)
   at Pk.MessageBus.Framework.MessageBusRegistry.MultiInstanceFactory(IContext ctx, Type t)

This doesn't seem to contain much "A depends on B which depends on A depending on B" type of clues.

**Comment by jeremydmiller** [comment]
What is your `MultiInstanceFactory`?

**Comment by jeremydmiller** [comment]
You don't have some kind of caching issue where you're accidentally reusing a nested container somehow, are you? When this exception happens, can you check the Container.Role and see what it is? That's the only explanation I can think of for the stack trace you see above.

**Comment by JKSnd** [comment]
It simply defers to the container, with a little try/catch to wrap exceptions in an exception that's particular to a MediatR wrapper we use. This is mainly to enable a "bool TrySend<TResponse>(IRequest msg, out TResponse response)" method.

```
private static IEnumerable<object> MultiInstanceFactory(IContext ctx, Type t)
{
  try
  {
    return ctx.GetAllInstances(t);
  }
  catch (StructureMapException e)
  {
    throw new HandlerNotFoundException($"No handlers found for message type {t.ToString()}", e);
  }
}
```

Container.Role -- I'll look into that right now. What should I be expecting?

**Comment by jbogard** [comment]
No, MediatR only includes a couple of factory delegates, it's up to the user to configure the container.

**Comment by jeremydmiller** [comment]
@JKSnd Are you reusing that MultiInstanceFactory across requests?

**Comment by JKSnd** [comment]
That's correct. It is wired up one single time during startup

**Comment by JKSnd** [comment]
Container.Role is reporting "Root" in my tests.

**Comment by jeremydmiller** [comment]
Actually, just for fun, can you get rid of the `UniqueLifecycle` and see if that makes a difference?

**Comment by JKSnd** [comment]
Ok, removed the explicit lifecycles. 

- The test to resolve 30 AsyncNotificationHandler requests in parallel resulted in the same Bi-dir exception
- The tests to resolve more than 1 RequestHandler request in parallel resulted in some "An item with the same key has already been added" exceptions.

**Comment by jeremydmiller** [comment]
Alright. So I think I'm asking you to either fork SM's code and give it a shot, or can you add a PR to StructureMap with your failing tests and I'll look into it locally?

Unfortunately, I'm backed up on these kinds of things, so it'd be mid to late week for me.

**Comment by JKSnd** [comment]
Can do, stay tuned. Thanks for this!

**Comment by JKSnd** [comment]
Oh damn. I see that this project is using the new VS2017 project format. I'm still using 2015 as this is an awkward moment in our release cycle to update our tools.

The gist I created is a complete file, however. Dropping it into your local project and pulling the NuGet packages should be smooth as pie. Is that an option?

**Comment by JKSnd** [comment]
A couple observations:

- If I remove the message bus entirely and have the tests use the container to locate handlers directly, everything works fine. Either the likelihood of the issue manifesting becomes vanishingly small, or the issue is subverted.
- If I add locking around the single and multiple instance factory implementations, things behave themselves. This, however, is an obvious bottleneck and isn't a production-quality solution. Interesting, though.

**Comment by JKSnd** [comment]
@jeremydmiller after more field testing, I've now seen some "Collection modified after the enumerator was instantiated" exceptions coming from BuildSession.Pop(), and some "Index was outside the bounds of the array" exceptions from BuildSession.Push().

I've noticed that the underlying stack in BuildSession doesn't have any thread-safety measures in place. I think that is the likely cause of the problems I've been experiencing. What would you suggest, here?

**Comment by jeremydmiller** [comment]
That code shouldn't *have* to be thread safe. A BuildSession is only used for either a single call of any kind to `IContainer.GetInstance()`. I guess you could add some locking around the list or stack (don't remember which one it is). I'd be much more interested in trying to understand how in the world you're possibly getting multiple threads at that. Doing anything funky with construction by lambdas maybe?

**Comment by JKSnd** [comment]
The nature of the domain we're working in over here is highly concurrent. When this issue is observed, a fair number of threads are all making calls on the MediatR message bus, which does a GetInstance() each time.

Maybe it would help if I understood why having multiple threads in there is a surprise.

**Comment by jeremydmiller** [comment]
I can't think of any simple reason why you *would* ever have multiple threads ever hitting the same BuildSession because they are not reused between requests to Container.GetInstance(). Is there any place where MediatR or your code is doing some kind of parallel construction within a lambda that uses the `IContext`? Something like:

```
For<ISomething>().Use(c => {
    // start multiple threads or parallel actions that use the "c" here
});
```

Failing that, I'd wonder if MediatR itself is doing something that caches those things

**Comment by JKSnd** [comment]
Oh I see what you mean now, on each call to GetInstance a build session is new'd up with the current graph. I gotcha.

I'll review the registries for such lambdas.

**Comment by JKSnd** [comment]
Hmm. This seems to have become one hell of a puzzle. There isn't any parallel funny-business going down in any of the construction lambdas (of which there are very few).

It looks like StructureMap does a good job of not spilling its guts, so I'm not sure how MediatR would get its hands on that stack to cache it.

**Comment by jeremydmiller** [comment]
One last thing to look for that I should have gone for right off the bat. Is there any place where it might be injecting a Func<T> or a Lazy<T> that gets kept around outside of the lifetime of the request? Thinking the Func<T> could actually be an issue, and kinda remember someone else having similar issues with that

**Comment by JKSnd** [comment]
Oooooooooo ok you might be onto something. Especially since you mentioned seeing something similar before with MediatR + SM.

We use a singleton instance of a MediatR.Mediator object as our message bus. This is where the MultiInstanceFactory (from above) is used, and it is simply a delegate. The Mediator gets this delegate from SM and holds onto it forever, using it for each request.

Could this be the culprit? [Here's the Mediator source.](https://github.com/jbogard/MediatR/blob/master/src/MediatR/Mediator.cs)

**Comment by jeremydmiller** [comment]
Maybe. What's your StructureMap adapter to Mediatr look like?

**Comment by JKSnd** [comment]
Here's the registry we're using to wire that all up.

    public class MessageBusRegistry : Registry{
        public MessageBusRegistry()
        {
          this.Scan(s =>
          {
            s.AssembliesAndExecutablesFromApplicationBaseDirectory(a => a.FullName.ToUpper().Contains("PK"));
            s.TheCallingAssembly();
        
            s.ConnectImplementationsToTypesClosing(typeof(IRequestHandler<,>)).OnAddedPluginTypes(e => e.LifecycleIs(new UniquePerRequestLifecycle()));
            s.ConnectImplementationsToTypesClosing(typeof(IAsyncRequestHandler<,>)).OnAddedPluginTypes(e => e.LifecycleIs(new UniquePerRequestLifecycle()));
            s.ConnectImplementationsToTypesClosing(typeof(INotificationHandler<>)).OnAddedPluginTypes(e => e.LifecycleIs(new UniquePerRequestLifecycle()));
            s.ConnectImplementationsToTypesClosing(typeof(IAsyncNotificationHandler<>)).OnAddedPluginTypes(e => e.LifecycleIs(new UniquePerRequestLifecycle()));
            s.ConnectImplementationsToTypesClosing(typeof(ICancellableAsyncRequestHandler<,>)).OnAddedPluginTypes(e => e.LifecycleIs(new UniquePerRequestLifecycle()));
            
          });
            
          this.For<IMessageBus>().Use<MessageBus>().Singleton();
          
          this.For<SingleInstanceFactory>().Use<SingleInstanceFactory>(ctx => t => SingleInstanceFactory(ctx, t));
          this.For<MultiInstanceFactory>().Use<MultiInstanceFactory>(ctx => t => MultiInstanceFactory(ctx, t));
        }
        
        
          private static object SingleInstanceFactory(IContext ctx, Type t)
          {
            try
            {
            return ctx.GetInstance(t);
          }
            catch (StructureMapException e)
            {
              throw new HandlerNotFoundException($"No handler found for message type {t.ToString()}", e);
            }
          }
        
        
        private static IEnumerable<object> MultiInstanceFactory(IContext ctx, Type t)
        {
          try
          {
            return ctx.GetAllInstances(t);
          }
          catch (StructureMapException e)
          {
            throw new HandlerNotFoundException($"No handlers found for message type {t.ToString()}", e);
          }
        }
    }

**Comment by jeremydmiller** [comment]
Ugh, yeah, that's your culprit if you use Single/Multiple factory outside of the context of creating an object through SM. Like if you cache those objects somewhere and reuse them outside of its original context.

**Comment by JKSnd** [comment]
Ok! Very interesting, as we're essentially following the [MediatR sample recommendation](https://github.com/jbogard/MediatR/blob/master/samples/MediatR.Examples.StructureMap/Program.cs).

Do you have any recommendations on how to properly integrate these two?

**Comment by jeremydmiller** [comment]
Shoot, gimme a couple days, let me pull down the MediatR code to understand what *it's* doing and I'll get back to you. Sorry for the constant delays

**Comment by JKSnd** [comment]
Thanks so much! We appreciate your time. You've inspired a couple ideas on this end that we'll try out. I'll let you know if we uncover any solutions.

**Comment by JKSnd** [comment]
Just an FYI so we can avoid wasting your time if possible.
We rubbed our brains together over here and, using your insight, came up with a solution that we think is viable. We verified our fix with unit tests that we consider reasonable. I'll update soon with what we've done just to make sure you don't see any huge red flags.

**Comment by JKSnd** [comment]
OK! So I've created an issue on the MediatR project:  jbogard/MediatR#194

It boils down to me suggesting [this Gist](https://gist.github.com/JKSnd/7c28077d9cfbcccc50f9cdbd762c775b) be used in the SM + MR sample. Does it seem like an acceptable solution from your perspective?

**Comment by jbogard** [comment]
And I don't think that gist will work as a general solution, it's using static and global state. IMediator is meant to be a transient dependency (at most, per-request), see:

https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/blob/master/src/MediatR.Extensions.Microsoft.DependencyInjection/ServiceCollectionExtensions.cs#L300

**Comment by jbogard** [comment]
I've clarified the example in the MediatR samples. Essentially, the sample relied on the default SM behavior of transient lifecycle - which is the correct lifecycle for the mediator instance. I've made that explicit so that you don't try to elevate its lifecycle to something stickier like singleton etc. It's meant to be at most per-request, but transient is best.

**Comment by jbogard** [comment]
@jeremydmiller i think you can close this one now.

**Comment by JKSnd** [comment]
Thanks for your time and effort @jeremydmiller and @jbogard!

**Comment by JKSnd** [comment]
Wait, @jeremydmiller I think I'm still fuzzy on some detail here since I've taken the suggestions @jbogard gave and the issues came back. 

Here's whats up: Ran my concurrency tests in the style of the new sample (explicit transient and again with always unique lifecycles for the IMediator), using the same style of expressions for the factories, and saw the original errors manifest again. Moved the factory delegates into a wrapper again that gets injected with an IContainer and the errors disappeared. The wrapper itself is also transient in these most recent tests.

I think the issue is with using the IContext instead of IContainer. What is the major difference between constructing objects using an IContext vs an IContainer?

**Comment by jbogard** [comment]
What do your tests look like?

**Comment by JKSnd** [comment]
Here's a little expert.   

    [Trait("Category", "Unit Tests")]
    public class Concurrency_Tests
    {
        private readonly IMediator mediator;

        public Concurrency_Tests()
        {
        var container = new Container(cfg =>
                                        {
                                        cfg.AddRegistry<MessageBusRegistry>();
                                        });

        container.AssertConfigurationIsValid();

        this.mediator = container.GetInstance<IMediator>();
        }
        
        [Theory]
        [InlineData(1)]
        [InlineData(2)]
        [InlineData(10)]
        [InlineData(30)]
        public void ShouldHandleNotificationConcurrently(int parallelisation)
        {
        Action<int, ParallelLoopState> body = (i, state) => { this.mediator.Publish(new TestNotification()); };
        Parallel.For(0, parallelisation, body);
        }
    }

**Comment by jbogard** [comment]
This test still uses a single mediator instance in parallel. It should not.

**Comment by jbogard** [comment]
This is a better test that should match your actual usage:

```c#
[Trait("Category", "Unit Tests")]
public class Concurrency_Tests
{
    private readonly IContainer container;

    public Concurrency_Tests()
    {
    this.container = new Container(cfg =>
                                    {
                                    cfg.AddRegistry<MessageBusRegistry>();
                                    });

    container.AssertConfigurationIsValid();
    }
    
    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(10)]
    [InlineData(30)]
    public void ShouldHandleNotificationConcurrently(int parallelisation)
    {
    Action<int, ParallelLoopState> body = (i, state) => { container.GetInstance<IMediator>().Publish(new TestNotification()); };
    Parallel.For(0, parallelisation, body);
    }
}
```

**Comment by JKSnd** [comment]
Blegh! You're right. Silly mistake on my end. That change does work. Thanks again!

**Comment by jbogard** [comment]
So NOW you can close this :)
