### ISSUE TITLE
Documentation of Autofactory is missing 2 samples

### ISSUE THREAD

**Issue by frankbenoit** [structuremap/structuremap#609]
See http://structuremap.github.io/autofactory/

In the first paragraph, there are 2 of the 4 samples missing

Now you declare an interface for your factory:

Missing code sample 'ISimpleDummyFactory' -- Wait for dotnet stdocs to catch up reading samples or CTRL+SHIFT+R to force refresh

All you need to do is to call CreateFactory when configuring the container as shown below:

Missing code sample 'simple-factory' -- Wait for dotnet stdocs to catch up reading samples or CTRL+SHIFT+R to force refresh

**Comment by DixonDs** [comment]
@frankbenoit it should be fixed once live docs are updated next time. In the meantime, you can find those samples at https://github.com/structuremap/structuremap/blob/10d5ef59ecb9d003b619f868d4a9046e7addd4af/src/StructureMap.AutoFactory.Testing/Samples.cs
