### ISSUE TITLE
Possible to avoid disposing singleton?

### ISSUE THREAD

**Issue by evanphillipsdsg** [structuremap/structuremap#610]
Hi,

I have a singleton that I am bringing in to StructureMap that I **don't** want to be automatically disposed when I dispose of the StructureMap container. I thought I could do this by creating my own lifecycle and object cache but even if I do that my singleton is disposed by the PluginGraph because of this code: https://github.com/structuremap/structuremap/blob/6dd07b75f882764d33dd97a851035432f9c98d58/src/StructureMap/Graph/PluginGraph.cs#L377-L390

Am I missing something? Is there any workaround for this?

Thanks,
Evan

**Comment by jeremydmiller** [comment]
@evanphillipsdsg There's nothing in SM itself for what you're needing here, but you can always get around it just by putting some kind of "disposal lock" in your code that ignores the Dispose() until you tear down your application

**Comment by evanphillipsdsg** [comment]
@jeremydmiller Alright, thanks for your response. I'll go ahead and do what you suggest.
