### ISSUE TITLE
Structuremap cannot find Instances from other projects

### ISSUE THREAD

**Issue by idotnetdev** [structuremap/structuremap#613]
Hi
I am using structuremap in my Work Projects.
After I updated structremap version to latest version and change my codes to latest, structremap cannot find any instances from other projects which has refrences from than.
[AutoMapperSample.zip](https://github.com/structuremap/structuremap/files/1353352/AutoMapperSample.zip)

In my case I have class (Automapper Profile) and interface (IHaveCustomMappings).
I have to get instances of any of this class and interfaces in project Ioc but i can not.
Please help me.

**Comment by jeremydmiller** [comment]
Can you start with this? http://structuremap.github.io/diagnostics/type-scanning/. My guess is that it's not finding the assemblies it should be.

**Comment by idotnetdev** [comment]
Thanks for reply.
I don't understand how i use type scanning in my project.
I get this report from WhatDidIScan() method:
`All Scanners
================================================================
Scanner #1
Assemblies
----------
* AutoMapperProfiles, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
* Ioc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Conventions
--------
* Default I[Name]/[Name] registration convention


AutoMapperRegistry Scanner #1
Assemblies
----------
* Ioc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Conventions
--------
* Default I[Name]/[Name] registration convention


No problems were encountered in exporting types from Assemblies
`
Can you run my attached project files please? you may help me about this problem. I have this problem for two weeks.

**Comment by jeremydmiller** [comment]
@idotnetdev I'm sorry, but I really just don't have the bandwidth to run the project for you.
