### ISSUE TITLE
DefaultConventionScanner can't match generic interfaces

### ISSUE THREAD

**Issue by rubenmonteiro** [structuremap/structuremap#617]
Hi.
I'm having some problems creating a class, the class is the following
`public class AdvancedTechnologiesManager : BaseManager<IAdvTechRepository>, IAdvancedTechnologiesManager<IAdvTechRepository>`
My registry is the following
```
public DefaultRegistry() {
            Scan(
                scan => {
                    scan.TheCallingAssembly();
                    scan.AssembliesAndExecutablesFromApplicationBaseDirectory();
                    scan.WithDefaultConventions();
					scan.With(new ControllerConvention());
                });
        }
```

I was expecting that when I tried to get the IAdvancedTechnologiesManager interface it would instantiate the  AdvancedTechnologiesManager class, but that didn't happen.

So I had to fork the code to check what was happening, and I found that on DefaultConventionScanner the method FindPluginType did match the class to the interface
![i19 cimgpsh_orig](https://user-images.githubusercontent.com/33164559/32124260-128c5170-bb5f-11e7-9dd2-3433541afc16.png)
And by doing so it doesn't create the object

I this the expected behavior?
Best regards, Ruben

**Comment by jeremydmiller** [comment]
@rubenmonteiro You might wanna check out this: http://structuremap.github.io/generics/ 

The default scanning wouldn't catch on your scenario up above.

*This* would have worked:

```
AdvancedTechnologiesManager : BaseManager<IAdvTechRepository>, IAdvancedTechnologiesManager
```

or go for the "connect all implementing" thing in the link from above.

**Comment by rubenmonteiro** [comment]
@jeremydmiller Thanks for the reply, but should the default scanning catch them?

**Comment by jeremydmiller** [comment]
The behavior you're reporting here is working as designed and as documented.

**Comment by rubenmonteiro** [comment]
ok
