### ISSUE TITLE
StructureMap cann't resolve dependencies when using child container.

### ISSUE THREAD

**Issue by zordark** [structuremap/structuremap#618]
Hello, I use StructureMap as replacement of standard container in asp.net core and get strange behavior when use child containers. 
I manually instantiate Startup class and pass pre-configured container to it.
My Startup.cs looks like this:
```c#
  public class Startup : IStartup {
        private IContainer _container;
        public Startup(IConfiguration configuration, IContainer container)
        {
            Configuration = configuration;
            _container = container;
       }

        public IConfiguration Configuration { get; }

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            // Register additional stuff
            // .....

            // populate the container using the service collection.
            _container.Populate(services);

            return _container.GetInstance<IServiceProvider>();
        }
        public void Configure(IApplicationBuilder app)
        {
             //do additional work 
        }
    }
```
And build host like this:
```c#
            var container = new Container();

            var configurationBuilder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json");

            var configuration = configurationBuilder.Build();

            var startup = new Startup(configuration, container);

            var builder = WebHost.CreateDefaultBuilder()
                .UseSetting(WebHostDefaults.ApplicationKey, typeof(Startup).Assembly.GetName().Name)
                .ConfigureServices(services => services.AddSingleton<IStartup>(startup))
                .UseKestrel(options =>
                {
                    options.Listen(IPAddress.Loopback, 1113);
                });

            var host = builder.Build();
```

It's work perfectly, until I start to use child container for my Strartup class.
Following code will fail:
```c#
            var container = new Container();

            var configurationBuilder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json");

            var configuration = configurationBuilder.Build();

            var startup = new Startup(configuration,  container.CreateChildContainer());

            var builder = WebHost.CreateDefaultBuilder()
                .UseSetting(WebHostDefaults.ApplicationKey, typeof(Startup).Assembly.GetName().Name)
                .ConfigureServices(services => services.AddSingleton<IStartup>(startup))
                .UseKestrel(options =>
                {
                    options.Listen(IPAddress.Loopback, 1113);
                });

            var host = builder.Build();
```
with exception: `StructureMap.StructureMapConfigurationException : No default Instance is registered and cannot be automatically determined for type 'IOptions<KestrelServerOptions>'`
It's happens inside WebHost class, when it try to resolve `IServer` instance.

Why is it happens?

**Comment by jeremydmiller** [comment]
Meh, this has come up a couple times now. The policies that do the automatic closing of open generic candidates only apply in the root container. Your use case isn't something I ever anticipated folks doing.

You could cheat this by first resolving that service in the root container before using the child container. First though, what's the point in using a child container here?

**Comment by zordark** [comment]
It's some kind of webhost orchestration system. 
Application manage many IWebHost instances, and I can't share the same container between it, because each host have they own configuration of services.
But I have some common configuration for all hosts.
Using child containers exactly what I need, according documentation.
At now, I use workaround: I create individual container for each host and initialize it with common configuration. But it's not best solution. And I can't use solution you provide, because I don't know  exactly, what each host registered in child container. Application just offer infrastructure for each host.

**Comment by dazinator** [comment]
Wondering why this is closed? Please see https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/issues/43 for related issue. Is this closed because it's not considered a bug? I'm not really sure what to do to overcome this issue so I have had to switch to autofac where IOptions<T> and child containers works as expected.

**Comment by jeremydmiller** [comment]
@dazinator StructureMap is no longer actively supported

**Comment by dazinator** [comment]
@jeremydmiller Oh right - apologies I hadn't realised. I'll take a look at Lamar, and I'll probably stick with autofac for now. Cheers
