### ISSUE TITLE
Structuremap loading assemblies from sub folders

### ISSUE THREAD

**Issue by nazirsj** [structuremap/structuremap#619]
I have a service that uses application domains. A few legacy domains living in isolation and work supervised via a main process.

The main application and sub processes have different IOC containers.

With version 4.2.0.402 of structuremap I noticed that "AssembliesAndExecutablesFromPath" is loading all assemblies, even the binaries from sub process folder(s) - this is causing a bit of a nightmare.

The app domains also load the configuration as the main process but parts of it. So excluding a folder in the scan is not an option.

**Comment by jeremydmiller** [comment]
Can you just use `AssembliesFromPath()` instead? The whole point of `AssembliesAndExecutablesFromPath` was to also scan executable files.

**Comment by nazirsj** [comment]
I tried that, even in version 4.5.1 and it also loads sub folders. I made sure there were no registries in the sub-folder that did a further scan when I tested it.

I reverted to the following bit of code:
`        public static bool CheckAssemblyExistsInExecutingAssemblyLocation(Assembly assembly)
        {
            var assemblyName = System.Reflection.Assembly.GetExecutingAssembly().FullName;
            var processPath = System.Reflection.Assembly.GetExecutingAssembly().Location;
            var processFolder = System.IO.Path.GetDirectoryName(processPath);
            return (System.IO.Path.GetDirectoryName(assembly.Location) == processFolder);
        }`
