### ISSUE TITLE
Singleton open generic returns new instance

### ISSUE THREAD

**Issue by eben-roux** [structuremap/structuremap#635]
Using the following:

```
    var registry = new Registry();

    registry.For(typeof(IOpenGeneric<>)).Use(typeof(OpenGeneric<>)).Singleton();

    var resolver = new Container(registry);

    var string1 = resolver.GetInstance<IOpenGeneric<string>>();
    var string2 = resolver.GetInstance<IOpenGeneric<string>>();

    Console.WriteLine(string1 == string2);
```

The `string2` instance is not equal to the `string2` instance.  

I have a bit of an adapter going for the major DI containers and this is the only test that is failing.  It isn't a train smash but I thought I'd let you know.  [StructureMap is here](https://github.com/Shuttle/Shuttle.Core.StructureMap).

I have a request from the Castle folks for a PR regarding checking whether a specific `ISubDependencyResolver` has been registered and haven't gotten around to that.  If you'd like a PR I'll add it to my backlog :)

**Comment by jeremydmiller** [comment]
@eben-roux It will work if you change your registration to: 

```
registry.ForSingletonOf(typeof(IOpenGeneric<>)).Use(typeof(OpenGeneric<>));
```

If you want to do the PR for the fix, it's just copying over the lifecycle in this code: https://github.com/structuremap/structuremap/blob/master/src/StructureMap/Pipeline/ConstructorInstance.cs#L146

**Comment by eben-roux** [comment]
Excellent, that did the trick, thanks Jeremy.

Any reason you have more than one mechanism or is it just for convenience?

**Comment by jeremydmiller** [comment]
Historical accident. Way back when you only set the lifecycle at the plugin type level.
