### ISSUE TITLE
Named instances do not support Lazy<> or Func<>

### ISSUE THREAD

**Issue by FC-KevinD** [structuremap/structuremap#641]
Consider the following classes:

    public class Foo : IFoo
    {
        private readonly string _val;

        public Foo(string val)
        {
            _val = val;
        }

        public string GetFoo() => _val;
    }

    public class Bar : IBar
    {
        private readonly Lazy<IFoo> _foo;

        public Bar(Lazy<IFoo> foo)
        {
            _foo = foo;
        }

        public string GetBar() => _foo.Value.GetFoo();
    }

With these registrations:

    For<IFoo>()
        .Add<Foo>().Named("alpha")
        .Ctor<string>().Is("alpha");

    For<IFoo>()
        .Add<Foo>().Named("bravo")
        .Ctor<string>().Is("bravo");

    For<IBar>().Use<Bar>()
        .Ctor<IFoo>().Named("alpha");

When the `Bar`'s `Lazy<IFoo>` is evaluated I would expect it to get the "alpha" instance of `IFoo` but instead StructureMap throws an exception indicating there is no default instance registered for the `IFoo` interface. Swapping `Named()` for `IsNamedInstance()` in the registration for `Bar` has the same result.

What users have to do to actually produce the expected functionality is this:

    For<IBar>().Use<Bar>()
        .Ctor<Lazy<IFoo>>().Is(context => new Lazy<IFoo>(() => context.TryGetInstance<IFoo>("alpha")));

**Comment by jeremydmiller** [comment]
@FC-KevinD See the discussion about "Use() vs Add()" in the documentation: http://structuremap.github.io/registration/registry-dsl/.

That's all working as designed.
