### ISSUE TITLE
Question: When does Container.GetInstance<> return a new object?

### ISSUE THREAD

**Issue by shaulbehr** [structuremap/structuremap#643]
I've got two branches of code, and the following test:
```
        [Test]
        public void DeleteThis()
        {
            var repo1 = FixtureContainer.GetInstance<IAlertRepository>();
            var repo2 = FixtureContainer.GetInstance<IAlertRepository>();
            repo1.GetHashCode().ShouldNotEqual(repo2.GetHashCode());
        }
```
In branch 1, this test passes; in branch 2 it fails. Obviously something in the container's configuration has changed between branch 1 and branch 2, so that in branch 2 the container is caching objects rather than creating them anew with each invocation. But what?

**Comment by jeremydmiller** [comment]
@shaulbehr Have you looked at the WhatDoIHave() output?

**Comment by shaulbehr** [comment]
@jeremydmiller branch 2 is a nested container. Other than that, no difference I can see.

**Comment by jeremydmiller** [comment]
Did you check the WhatDoIHave() output? What's the lifecycle for that service? If you look at the docs on nested containers, the lifecycle rules are slightly different

**Comment by shaulbehr** [comment]
[wdih5.5.txt](https://github.com/structuremap/structuremap/files/1830502/wdih5.5.txt)
[wdih5.6.txt](https://github.com/structuremap/structuremap/files/1830503/wdih5.6.txt)

Here are the two WhatDoIHave() results. Not sure how to read this.

**Comment by shaulbehr** [comment]
Not sure which docs to look at, what are the main differences?

**Comment by jeremydmiller** [comment]
http://structuremap.github.io/the-container/nested-containers/

**Comment by shaulbehr** [comment]
Aha. That was a little counter-intuitive, unless I've misunderstood the purpose of nested containers. I didn't expect the behavior of a nested container to be different from the parent container.
How do I get the nested container to have the same behavior, i.e. creating a new instance of the requested object?

**Comment by jeremydmiller** [comment]
http://structuremap.github.io/object-lifecycle/supported-lifecycles/

**Comment by shaulbehr** [comment]
OK, so it looks like I want the `AlwaysUnique` behavior. Is there a way to define that as the behavior for the whole nested container? The examples show how to define the lifecycle for specific types, not the whole container.

**Comment by jeremydmiller** [comment]
Not directly, but I guess you could write a custom IInstancePolicy to force it. IMO, most of the time you want exactly the nested behavior as it's built now. If you were using SM through the ASP.Net DI abstractions, it de facto registers their "transient" as SM's AlwaysUnique.

**Comment by shaulbehr** [comment]
It's a bit of an edge case I'm trying to work with here; it's an integration test fixture that I'm trying to run in multiple threads. So I need a different container for each thread (hence the nested containers), but each container might be connecting to different databases with identical schema via repository classes, so each time I get the repository class I want a new one so it injects the right db context.
Am I abusing the idea of a nested repository here, then?

**Comment by jeremydmiller** [comment]
The nested container is meant to be used for short lived operations like HTTP requests or service bus messages being handled, that's why the scoping is different. You might want a child container instead in your case.

**Comment by shaulbehr** [comment]
Excellent, that's exactly what I need: a child container. Glad I asked; I had no idea there was such a thing; that what I thought the nested container was.
Thanks so much for your help, and especially for being so amazingly responsive and patient!
