### ISSUE TITLE
Can .Named take a null and then ignore it

### ISSUE THREAD

**Issue by phatcher** [structuremap/structuremap#649]
I'm porting some code from Unity and my library uses something similar to Registry classes.

What I find is that I'm having to write a lot of conditional code due to Named not taking/ignoring a null key e.g. 
```
 var expr = container.For<IApiCredentials>().LifecycleIs(Lifetime.ToLifecycle()).Use<TCredentials>();
 if (!string.IsNullOrEmpty(Id))
 {
    expr.Named(Id);
 }
```
where Id is a string property of the surrounding class.

Is there a better way of doing a conditional registration of the name?

**Comment by jeremydmiller** [comment]
You could write an extension method to do what you need to do there w/o the extra code noise. Before you go too far w/ your conversion, you did see that SM is deprecated?

**Comment by phatcher** [comment]
Ah that's a good idea..

I saw the deprecation this afternoon, I already have some code written so I'll continue for now as I need net framework as well as netstandard

**Comment by jeremydmiller** [comment]
@phatcher See the discussion of `Add()` vs. `Use()` in the docs

**Comment by phatcher** [comment]
@jeremydmiller I did, it appears that calling `.Use` create/replaces the default registration even if it's named whereas I'm used to named instances only being stored against their specified name and retrieved if they are explicitly requested or if you retrieve all registered instances (Unity/Castle Windsor).

The problem arises in that if I am registering multiple sets of components some all wired together with instance names and the default using the "unnamed" registration and a programmer changes the order of the components or adds a new one, then potentially the default registration is going to cross-wire since the last `.Use` registration will replace its intended dependencies, so I have to have conditional code as above.

Don't expect you to do anything, just seemed to violate "Least surprise"

**Comment by jeremydmiller** [comment]
"just seemed to violate "Least surprise"" -- a lot of different containers would have had similar behavior to StructureMap for the "last one wins" registrations as well as the new built in DI container in ASP.net Core. StructureMap was and is the only single container I'm aware of that let's you do the Use() v. Add() semantics, so in that way SM *is* better for what you're doing here.
