### ISSUE TITLE
Structuremap causing stackoverflow exception

### ISSUE THREAD

**Issue by Salalimo** [structuremap/structuremap#650]
I have a few projects that I am using structuremap, and today all of them are throwing stackoverflow exception. Even this small program:

     static void Main(string[] args)
     {
            var container = Container.For<ConsoleRegistry>();
     }

    public class ConsoleRegistry : Registry
    {
        public ConsoleRegistry()
        {
            For<IFoo>().Use<Foo>();//exception thrown here
        }
    }
    public class Foo : IFoo
    {
        public string Print()
        {
            return "hello";
        }
    }

    public interface IFoo
    {
        string Print();
    }

The only thing I can think of is that something on my machine has changed.. and I have installed .net framework 4.7.2. 

Any ideas on how to resolve this would be appreciated. 
Thanks.

**Comment by Salalimo** [comment]
For<IFoo>().Use<Foo>();
The line above is where the exception happens.. and this is all of the code in the console application that I am running.. 



When I use the Scan method below it works and I can do something like
          var fooInstance = container.GetInstance<Foo>();
          var result = fooInstance.Print();

Scan(scan =>
            {
                scan.TheCallingAssembly();
                scan.WithDefaultConventions();
            });

**Comment by Salalimo** [comment]
Just to follow up... 

Using the source the exception is thrown at 

    return new Container(new T()); //line 25 in the container class..

If I break down that line it happens at  new T();
var x = new T();

If I hover over the line I get the following message

![image](https://user-images.githubusercontent.com/37840650/44370953-86eee980-a4aa-11e8-9f67-02d420ca25c2.png)


so it is most likely something to do with my machine.. but I am not sure what it is.. 

Thanks for your quick response earlier.

**Comment by jeremydmiller** [comment]
As I said earlier, there's something else going on you're not showing me here. There's a bazillion tests in the StructureMap codebase that do exactly what you're showing there and the damn thing is 15 years old. There's something else going on in your setup

**Comment by robertmujica** [comment]
my 2 cents we start seeing Stackoverflow exception in PROD pointing to following call stack:


DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, StructureMap.IBuildSession, StructureMap.IContext)    StructureMap.Building.BuildPlan.Build(StructureMap.IBuildSession, StructureMap.IContext)    StructureMap.SessionCache.GetObject(System.Type, StructureMap.Pipeline.Instance, StructureMap.Pipeline.ILifecycle)
--


and looking at our code we noticed we are doing something stupid in a ctor of a class that is being injected by Structmap, that when an exception happens it bubble up to Structmap and cause the stackoverflow. We are 99% sure Structmap is correct, so it is just our logic.

@jeremydmiller does it make senses ?

**Comment by jeremydmiller** [comment]
@robertmujica I honestly don't know without a lot more context. From this issue, I'm 99% sure it was something funky they were doing in their bootstrapping code, but you're seeing problems at runtime.

**Comment by robertmujica** [comment]
@jeremydmiller this is a screenshot of what we seeing on dump file from PROD. But like i said i think we had a code in ctor what was making DB call and was raising a custom exception ( this is a normal scenario ) but because this was thrown within ctor, somehow this cause issue on StructMap.Pipeline.ILifecycle.

![image](https://user-images.githubusercontent.com/3818935/55003369-33a8c080-4fd0-11e9-9596-3764799058e6.png)

**Comment by jeremydmiller** [comment]
So it's definitely triggered by a problem in your code, but I'm not really sure why SM itself would be causing the StackOverflowException. Not claiming it's *not* causing the SO exception either.

As a matter of best practices though, I would recommend you don't really *do* much in constructor functions other than set up fields. In my work, I'd opt for some kind of "Initialize()" or "Start()" code to explicitly mark where work is starting.

**Comment by robertmujica** [comment]
Totally agree with you, I corrected the code by moving those lines from ctor to actual place where it is being used. I just wanted to shared this scenario here to get feedback from Structmap side.

**Comment by Salalimo** [comment]
I should have posted a followup when this issue was resolved. The exception I was having was due to a visual studio bug that since has been fixed in v15.9. The exception was triggered when a certain intellitrace option was selected. Under options->Intellitrace in visual studio if you selected anything other than the first option the exception would happen.  See image below.

![image002](https://user-images.githubusercontent.com/37840650/55008895-1bc54280-4fb8-11e9-82bb-4da6b5a0bf44.png)

Regards.

**Comment by jeremydmiller** [comment]
@Salalimo WTH. That's out of left field for me. I'm going to close this one on that.
