### ISSUE TITLE
Multiple calls to Configure on Container

### ISSUE THREAD

**Issue by no1melman** [structuremap/structuremap#653]
For this code here, and looking at PipelineGraph I'm trying to understand whether doing multiple calls to `Container.Configure()` is commutative thus allowing you to keep "adding" configures to the graph - that doesn't overwrite older configures?

https://github.com/structuremap/structuremap/blob/a2c453569ea8a5b084232522d37bdf9630f7362d/src/StructureMap/Container.cs#L800-L816

So something like

```

     var container = new Container ( cfg => {  /* do something base configuration */ } );
     container.Configure(cfg => { /* add some more config */ } );

```

In my eyes, that should keep both configurations, and just added them together

**Comment by jeremydmiller** [comment]
Container.Configure() is additive. I've always tried to recommend against using that too much in favor of trying to lock things down upfront, but so it goes.

**Comment by no1melman** [comment]
What you recommend in place - is there a configurationexpression object that we can pass around to add to?
