### ISSUE TITLE
nested container get disposed.

### ISSUE THREAD

**Issue by yuren1978** [structuremap/structuremap#665]
We are using nested container within asp.net web api project, however, we are seeing this exception get throw when try to resolve object with GetInstance

ObjectDisposedException("StructureMap Nested Container");

It looks like assertNotDisposed is throwing this exception, but I cannot understand why it would cause that, we cannot reproduce this issue locally, it only happens under a load. Any help?

Why a container will get disposed in the middle of http request?
```
    private void assertNotDisposed()
        {
            if (!_disposedLatch) return;
            switch (Role)
            {
                case ContainerRole.Root:
                    throw new ObjectDisposedException("StructureMap Application Root Container");
                case ContainerRole.Nested:
                    throw new ObjectDisposedException("StructureMap Nested Container");
                case ContainerRole.ProfileOrChild:
                    throw new ObjectDisposedException("StructureMap Child/Profile Container");
            }
        }
 ```

**Comment by FilipeDominguesGit** [comment]
Hi @yuren1978 ! did you manage to fix this? I'm having the exact same issue under load...
